//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.tfmrequestreplytypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for airlineSurfaceDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="airlineSurfaceDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IOBT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EOBT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="depStandAssignment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="arrStandAssignment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="arrStandAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="tmatRelinquish" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="tmatMarkedForSub" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="aircraftRegMark" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}aircraftRegMarkType" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="accDepRwy" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}runwayNameType" maxOccurs="7"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="unaccDepRwy" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}runwayNameType" maxOccurs="7"/>
 *         &lt;/sequence>
 *         &lt;element name="depReadiness" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="depIntentToHoldNonMove" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="arrIntentToHoldNonMove" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="depIntentToHoldInMove" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                 &lt;attribute name="holdIntent">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="HOLD"/>
 *                       &lt;enumeration value="NO_HOLD"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="estimatedEntryTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="arrIntentToHoldInMove" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                 &lt;attribute name="holdIntent">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="HOLD"/>
 *                       &lt;enumeration value="NO_HOLD"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="estimatedExitTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="intentToBeDeiced" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="intendedDeiceLocation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="intendedDepSpot" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="intendedArrSpot" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="intentReturnToGate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AOBT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="AIBT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ATOT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ALDT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "airlineSurfaceDataType", propOrder = {
    "iobt",
    "eobt",
    "depStandAssignment",
    "arrStandAssignment",
    "arrStandAvailable",
    "tmatRelinquish",
    "tmatMarkedForSub",
    "aircraftRegMark",
    "accDepRwy",
    "unaccDepRwy",
    "depReadiness",
    "depIntentToHoldNonMove",
    "arrIntentToHoldNonMove",
    "depIntentToHoldInMove",
    "arrIntentToHoldInMove",
    "intentToBeDeiced",
    "intendedDeiceLocation",
    "intendedDepSpot",
    "intendedArrSpot",
    "intentReturnToGate",
    "aobt",
    "aibt",
    "atot",
    "aldt"
})
public class AirlineSurfaceDataType {

    @XmlElement(name = "IOBT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar iobt;
    @XmlElement(name = "EOBT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eobt;
    protected String depStandAssignment;
    protected String arrStandAssignment;
    protected Boolean arrStandAvailable;
    protected Boolean tmatRelinquish;
    protected Boolean tmatMarkedForSub;
    protected String aircraftRegMark;
    protected List<String> accDepRwy;
    protected List<String> unaccDepRwy;
    protected Boolean depReadiness;
    protected Boolean depIntentToHoldNonMove;
    protected Boolean arrIntentToHoldNonMove;
    protected AirlineSurfaceDataType.DepIntentToHoldInMove depIntentToHoldInMove;
    protected AirlineSurfaceDataType.ArrIntentToHoldInMove arrIntentToHoldInMove;
    protected Boolean intentToBeDeiced;
    protected String intendedDeiceLocation;
    protected String intendedDepSpot;
    protected String intendedArrSpot;
    protected Boolean intentReturnToGate;
    @XmlElement(name = "AOBT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar aobt;
    @XmlElement(name = "AIBT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar aibt;
    @XmlElement(name = "ATOT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar atot;
    @XmlElement(name = "ALDT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar aldt;

    /**
     * Gets the value of the iobt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIOBT() {
        return iobt;
    }

    /**
     * Sets the value of the iobt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIOBT(XMLGregorianCalendar value) {
        this.iobt = value;
    }

    /**
     * Gets the value of the eobt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEOBT() {
        return eobt;
    }

    /**
     * Sets the value of the eobt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEOBT(XMLGregorianCalendar value) {
        this.eobt = value;
    }

    /**
     * Gets the value of the depStandAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepStandAssignment() {
        return depStandAssignment;
    }

    /**
     * Sets the value of the depStandAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepStandAssignment(String value) {
        this.depStandAssignment = value;
    }

    /**
     * Gets the value of the arrStandAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrStandAssignment() {
        return arrStandAssignment;
    }

    /**
     * Sets the value of the arrStandAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrStandAssignment(String value) {
        this.arrStandAssignment = value;
    }

    /**
     * Gets the value of the arrStandAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isArrStandAvailable() {
        return arrStandAvailable;
    }

    /**
     * Sets the value of the arrStandAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setArrStandAvailable(Boolean value) {
        this.arrStandAvailable = value;
    }

    /**
     * Gets the value of the tmatRelinquish property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTmatRelinquish() {
        return tmatRelinquish;
    }

    /**
     * Sets the value of the tmatRelinquish property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTmatRelinquish(Boolean value) {
        this.tmatRelinquish = value;
    }

    /**
     * Gets the value of the tmatMarkedForSub property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTmatMarkedForSub() {
        return tmatMarkedForSub;
    }

    /**
     * Sets the value of the tmatMarkedForSub property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTmatMarkedForSub(Boolean value) {
        this.tmatMarkedForSub = value;
    }

    /**
     * Gets the value of the aircraftRegMark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftRegMark() {
        return aircraftRegMark;
    }

    /**
     * Sets the value of the aircraftRegMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftRegMark(String value) {
        this.aircraftRegMark = value;
    }

    /**
     * Gets the value of the accDepRwy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accDepRwy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccDepRwy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAccDepRwy() {
        if (accDepRwy == null) {
            accDepRwy = new ArrayList<String>();
        }
        return this.accDepRwy;
    }

    /**
     * Gets the value of the unaccDepRwy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unaccDepRwy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnaccDepRwy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUnaccDepRwy() {
        if (unaccDepRwy == null) {
            unaccDepRwy = new ArrayList<String>();
        }
        return this.unaccDepRwy;
    }

    /**
     * Gets the value of the depReadiness property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepReadiness() {
        return depReadiness;
    }

    /**
     * Sets the value of the depReadiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepReadiness(Boolean value) {
        this.depReadiness = value;
    }

    /**
     * Gets the value of the depIntentToHoldNonMove property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepIntentToHoldNonMove() {
        return depIntentToHoldNonMove;
    }

    /**
     * Sets the value of the depIntentToHoldNonMove property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepIntentToHoldNonMove(Boolean value) {
        this.depIntentToHoldNonMove = value;
    }

    /**
     * Gets the value of the arrIntentToHoldNonMove property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isArrIntentToHoldNonMove() {
        return arrIntentToHoldNonMove;
    }

    /**
     * Sets the value of the arrIntentToHoldNonMove property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setArrIntentToHoldNonMove(Boolean value) {
        this.arrIntentToHoldNonMove = value;
    }

    /**
     * Gets the value of the depIntentToHoldInMove property.
     * 
     * @return
     *     possible object is
     *     {@link AirlineSurfaceDataType.DepIntentToHoldInMove }
     *     
     */
    public AirlineSurfaceDataType.DepIntentToHoldInMove getDepIntentToHoldInMove() {
        return depIntentToHoldInMove;
    }

    /**
     * Sets the value of the depIntentToHoldInMove property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirlineSurfaceDataType.DepIntentToHoldInMove }
     *     
     */
    public void setDepIntentToHoldInMove(AirlineSurfaceDataType.DepIntentToHoldInMove value) {
        this.depIntentToHoldInMove = value;
    }

    /**
     * Gets the value of the arrIntentToHoldInMove property.
     * 
     * @return
     *     possible object is
     *     {@link AirlineSurfaceDataType.ArrIntentToHoldInMove }
     *     
     */
    public AirlineSurfaceDataType.ArrIntentToHoldInMove getArrIntentToHoldInMove() {
        return arrIntentToHoldInMove;
    }

    /**
     * Sets the value of the arrIntentToHoldInMove property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirlineSurfaceDataType.ArrIntentToHoldInMove }
     *     
     */
    public void setArrIntentToHoldInMove(AirlineSurfaceDataType.ArrIntentToHoldInMove value) {
        this.arrIntentToHoldInMove = value;
    }

    /**
     * Gets the value of the intentToBeDeiced property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntentToBeDeiced() {
        return intentToBeDeiced;
    }

    /**
     * Sets the value of the intentToBeDeiced property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntentToBeDeiced(Boolean value) {
        this.intentToBeDeiced = value;
    }

    /**
     * Gets the value of the intendedDeiceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntendedDeiceLocation() {
        return intendedDeiceLocation;
    }

    /**
     * Sets the value of the intendedDeiceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntendedDeiceLocation(String value) {
        this.intendedDeiceLocation = value;
    }

    /**
     * Gets the value of the intendedDepSpot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntendedDepSpot() {
        return intendedDepSpot;
    }

    /**
     * Sets the value of the intendedDepSpot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntendedDepSpot(String value) {
        this.intendedDepSpot = value;
    }

    /**
     * Gets the value of the intendedArrSpot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntendedArrSpot() {
        return intendedArrSpot;
    }

    /**
     * Sets the value of the intendedArrSpot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntendedArrSpot(String value) {
        this.intendedArrSpot = value;
    }

    /**
     * Gets the value of the intentReturnToGate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntentReturnToGate() {
        return intentReturnToGate;
    }

    /**
     * Sets the value of the intentReturnToGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntentReturnToGate(Boolean value) {
        this.intentReturnToGate = value;
    }

    /**
     * Gets the value of the aobt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAOBT() {
        return aobt;
    }

    /**
     * Sets the value of the aobt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAOBT(XMLGregorianCalendar value) {
        this.aobt = value;
    }

    /**
     * Gets the value of the aibt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAIBT() {
        return aibt;
    }

    /**
     * Sets the value of the aibt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAIBT(XMLGregorianCalendar value) {
        this.aibt = value;
    }

    /**
     * Gets the value of the atot property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getATOT() {
        return atot;
    }

    /**
     * Sets the value of the atot property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setATOT(XMLGregorianCalendar value) {
        this.atot = value;
    }

    /**
     * Gets the value of the aldt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getALDT() {
        return aldt;
    }

    /**
     * Sets the value of the aldt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setALDT(XMLGregorianCalendar value) {
        this.aldt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *       &lt;attribute name="holdIntent">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="HOLD"/>
     *             &lt;enumeration value="NO_HOLD"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="estimatedExitTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ArrIntentToHoldInMove {

        @XmlValue
        protected boolean value;
        @XmlAttribute(name = "holdIntent")
        protected String holdIntent;
        @XmlAttribute(name = "estimatedExitTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar estimatedExitTime;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

        /**
         * Gets the value of the holdIntent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHoldIntent() {
            return holdIntent;
        }

        /**
         * Sets the value of the holdIntent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHoldIntent(String value) {
            this.holdIntent = value;
        }

        /**
         * Gets the value of the estimatedExitTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEstimatedExitTime() {
            return estimatedExitTime;
        }

        /**
         * Sets the value of the estimatedExitTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEstimatedExitTime(XMLGregorianCalendar value) {
            this.estimatedExitTime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *       &lt;attribute name="holdIntent">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="HOLD"/>
     *             &lt;enumeration value="NO_HOLD"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="estimatedEntryTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DepIntentToHoldInMove {

        @XmlValue
        protected boolean value;
        @XmlAttribute(name = "holdIntent")
        protected String holdIntent;
        @XmlAttribute(name = "estimatedEntryTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar estimatedEntryTime;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

        /**
         * Gets the value of the holdIntent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHoldIntent() {
            return holdIntent;
        }

        /**
         * Sets the value of the holdIntent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHoldIntent(String value) {
            this.holdIntent = value;
        }

        /**
         * Gets the value of the estimatedEntryTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEstimatedEntryTime() {
            return estimatedEntryTime;
        }

        /**
         * Sets the value of the estimatedEntryTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEstimatedEntryTime(XMLGregorianCalendar value) {
            this.estimatedEntryTime = value;
        }

    }

}
