//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.tfmrequestreplytypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.FiledFixType;


/**
 * NAS Field Reference: Field 06. NAS Format: This field may take the form of the following types: latLongType, fixNameType, fixRadialDistanceType.  Refer to these types
 *         for allowable formats. A fix mutually agreed upon by the facilities concerned for the coordination of center control transfer.
 * 
 * <p>Java class for coordinationPointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coordinationPointType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}filedFixType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coordinationPointType")
public class CoordinationPointType
    extends FiledFixType
{


}
