//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.tfmrequestreplytypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the override preview response type.
 * 
 * <p>Java class for overridePreviewResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="overridePreviewResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="waypointList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="edctRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "overridePreviewResponseType", propOrder = {
    "waypointList"
})
public class OverridePreviewResponseType {

    @XmlElement(required = true)
    protected String waypointList;
    @XmlAttribute(name = "edctRequired", required = true)
    protected boolean edctRequired;

    /**
     * Gets the value of the waypointList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaypointList() {
        return waypointList;
    }

    /**
     * Sets the value of the waypointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaypointList(String value) {
        this.waypointList = value;
    }

    /**
     * Gets the value of the edctRequired property.
     * 
     */
    public boolean isEdctRequired() {
        return edctRequired;
    }

    /**
     * Sets the value of the edctRequired property.
     * 
     */
    public void setEdctRequired(boolean value) {
        this.edctRequired = value;
    }

}
