//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.tfmrequestreplytypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Reroute model traffic counts data type.
 * 
 * <p>Java class for rriaTrafficCountsDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rriaTrafficCountsDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ctrHead">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rerouteId" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}rerouteIdType"/>
 *                   &lt;element name="rerouteName" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}rerouteNameType"/>
 *                   &lt;element name="modelTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="firstIntervalTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="lastIntervalTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="minutesInInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ctrSectorList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ctrCenter" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="centerName" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}airportIdType"/>
 *                             &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="ctrSector" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="sectorType">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="lowsec"/>
 *                                             &lt;enumeration value="highsec"/>
 *                                             &lt;enumeration value="superhisec"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="sectorName">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="10"/>
 *                                             &lt;pattern value="[A-Za-z0-9]*"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="sectorState">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="BASELINE"/>
 *                                             &lt;enumeration value="DYNAMIC"/>
 *                                             &lt;enumeration value="CLOSED"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="sectorsAdded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;sequence>
 *                                         &lt;element name="ctrBaselineData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrSectorDataCommon"/>
 *                                         &lt;element name="ctrDynamicData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrSectorDataCommon" minOccurs="0"/>
 *                                       &lt;/sequence>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ctrFixList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ctrFix" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fixName" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}fixNameType"/>
 *                             &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="ctrLowData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
 *                             &lt;element name="ctrHighData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
 *                             &lt;element name="ctrSuperHighData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ctrAirportList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ctrAirport" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="airportName" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}airportIdType"/>
 *                             &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;sequence>
 *                               &lt;element name="ctrDepartureData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
 *                               &lt;element name="ctrArrivalData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
 *                             &lt;/sequence>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rriaTrafficCountsDataType", propOrder = {
    "ctrHead",
    "ctrSectorList",
    "ctrFixList",
    "ctrAirportList"
})
public class RriaTrafficCountsDataType {

    @XmlElement(required = true)
    protected RriaTrafficCountsDataType.CtrHead ctrHead;
    @XmlElement(required = true)
    protected RriaTrafficCountsDataType.CtrSectorList ctrSectorList;
    protected RriaTrafficCountsDataType.CtrFixList ctrFixList;
    @XmlElement(required = true)
    protected RriaTrafficCountsDataType.CtrAirportList ctrAirportList;

    /**
     * Gets the value of the ctrHead property.
     * 
     * @return
     *     possible object is
     *     {@link RriaTrafficCountsDataType.CtrHead }
     *     
     */
    public RriaTrafficCountsDataType.CtrHead getCtrHead() {
        return ctrHead;
    }

    /**
     * Sets the value of the ctrHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link RriaTrafficCountsDataType.CtrHead }
     *     
     */
    public void setCtrHead(RriaTrafficCountsDataType.CtrHead value) {
        this.ctrHead = value;
    }

    /**
     * Gets the value of the ctrSectorList property.
     * 
     * @return
     *     possible object is
     *     {@link RriaTrafficCountsDataType.CtrSectorList }
     *     
     */
    public RriaTrafficCountsDataType.CtrSectorList getCtrSectorList() {
        return ctrSectorList;
    }

    /**
     * Sets the value of the ctrSectorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RriaTrafficCountsDataType.CtrSectorList }
     *     
     */
    public void setCtrSectorList(RriaTrafficCountsDataType.CtrSectorList value) {
        this.ctrSectorList = value;
    }

    /**
     * Gets the value of the ctrFixList property.
     * 
     * @return
     *     possible object is
     *     {@link RriaTrafficCountsDataType.CtrFixList }
     *     
     */
    public RriaTrafficCountsDataType.CtrFixList getCtrFixList() {
        return ctrFixList;
    }

    /**
     * Sets the value of the ctrFixList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RriaTrafficCountsDataType.CtrFixList }
     *     
     */
    public void setCtrFixList(RriaTrafficCountsDataType.CtrFixList value) {
        this.ctrFixList = value;
    }

    /**
     * Gets the value of the ctrAirportList property.
     * 
     * @return
     *     possible object is
     *     {@link RriaTrafficCountsDataType.CtrAirportList }
     *     
     */
    public RriaTrafficCountsDataType.CtrAirportList getCtrAirportList() {
        return ctrAirportList;
    }

    /**
     * Sets the value of the ctrAirportList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RriaTrafficCountsDataType.CtrAirportList }
     *     
     */
    public void setCtrAirportList(RriaTrafficCountsDataType.CtrAirportList value) {
        this.ctrAirportList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ctrAirport" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="airportName" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}airportIdType"/>
     *                   &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;sequence>
     *                     &lt;element name="ctrDepartureData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
     *                     &lt;element name="ctrArrivalData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
     *                   &lt;/sequence>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ctrAirport"
    })
    public static class CtrAirportList {

        @XmlElement(required = true)
        protected List<RriaTrafficCountsDataType.CtrAirportList.CtrAirport> ctrAirport;

        /**
         * Gets the value of the ctrAirport property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ctrAirport property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCtrAirport().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RriaTrafficCountsDataType.CtrAirportList.CtrAirport }
         * 
         * 
         */
        public List<RriaTrafficCountsDataType.CtrAirportList.CtrAirport> getCtrAirport() {
            if (ctrAirport == null) {
                ctrAirport = new ArrayList<RriaTrafficCountsDataType.CtrAirportList.CtrAirport>();
            }
            return this.ctrAirport;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="airportName" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}airportIdType"/>
         *         &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;sequence>
         *           &lt;element name="ctrDepartureData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
         *           &lt;element name="ctrArrivalData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
         *         &lt;/sequence>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "airportName",
            "impactedByReroute",
            "impactedByMit",
            "ctrDepartureData",
            "ctrArrivalData"
        })
        public static class CtrAirport {

            @XmlElement(required = true)
            protected String airportName;
            protected boolean impactedByReroute;
            protected boolean impactedByMit;
            @XmlElement(required = true)
            protected CtrPointDataCommon ctrDepartureData;
            @XmlElement(required = true)
            protected CtrPointDataCommon ctrArrivalData;

            /**
             * Gets the value of the airportName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAirportName() {
                return airportName;
            }

            /**
             * Sets the value of the airportName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAirportName(String value) {
                this.airportName = value;
            }

            /**
             * Gets the value of the impactedByReroute property.
             * 
             */
            public boolean isImpactedByReroute() {
                return impactedByReroute;
            }

            /**
             * Sets the value of the impactedByReroute property.
             * 
             */
            public void setImpactedByReroute(boolean value) {
                this.impactedByReroute = value;
            }

            /**
             * Gets the value of the impactedByMit property.
             * 
             */
            public boolean isImpactedByMit() {
                return impactedByMit;
            }

            /**
             * Sets the value of the impactedByMit property.
             * 
             */
            public void setImpactedByMit(boolean value) {
                this.impactedByMit = value;
            }

            /**
             * Gets the value of the ctrDepartureData property.
             * 
             * @return
             *     possible object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public CtrPointDataCommon getCtrDepartureData() {
                return ctrDepartureData;
            }

            /**
             * Sets the value of the ctrDepartureData property.
             * 
             * @param value
             *     allowed object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public void setCtrDepartureData(CtrPointDataCommon value) {
                this.ctrDepartureData = value;
            }

            /**
             * Gets the value of the ctrArrivalData property.
             * 
             * @return
             *     possible object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public CtrPointDataCommon getCtrArrivalData() {
                return ctrArrivalData;
            }

            /**
             * Sets the value of the ctrArrivalData property.
             * 
             * @param value
             *     allowed object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public void setCtrArrivalData(CtrPointDataCommon value) {
                this.ctrArrivalData = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ctrFix" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fixName" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}fixNameType"/>
     *                   &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="ctrLowData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
     *                   &lt;element name="ctrHighData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
     *                   &lt;element name="ctrSuperHighData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ctrFix"
    })
    public static class CtrFixList {

        @XmlElement(required = true)
        protected List<RriaTrafficCountsDataType.CtrFixList.CtrFix> ctrFix;

        /**
         * Gets the value of the ctrFix property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ctrFix property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCtrFix().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RriaTrafficCountsDataType.CtrFixList.CtrFix }
         * 
         * 
         */
        public List<RriaTrafficCountsDataType.CtrFixList.CtrFix> getCtrFix() {
            if (ctrFix == null) {
                ctrFix = new ArrayList<RriaTrafficCountsDataType.CtrFixList.CtrFix>();
            }
            return this.ctrFix;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fixName" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}fixNameType"/>
         *         &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="ctrLowData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
         *         &lt;element name="ctrHighData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
         *         &lt;element name="ctrSuperHighData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrPointDataCommon"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fixName",
            "impactedByReroute",
            "impactedByMit",
            "ctrLowData",
            "ctrHighData",
            "ctrSuperHighData"
        })
        public static class CtrFix {

            @XmlElement(required = true)
            protected String fixName;
            protected boolean impactedByReroute;
            protected boolean impactedByMit;
            @XmlElement(required = true)
            protected CtrPointDataCommon ctrLowData;
            @XmlElement(required = true)
            protected CtrPointDataCommon ctrHighData;
            @XmlElement(required = true)
            protected CtrPointDataCommon ctrSuperHighData;

            /**
             * Gets the value of the fixName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFixName() {
                return fixName;
            }

            /**
             * Sets the value of the fixName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFixName(String value) {
                this.fixName = value;
            }

            /**
             * Gets the value of the impactedByReroute property.
             * 
             */
            public boolean isImpactedByReroute() {
                return impactedByReroute;
            }

            /**
             * Sets the value of the impactedByReroute property.
             * 
             */
            public void setImpactedByReroute(boolean value) {
                this.impactedByReroute = value;
            }

            /**
             * Gets the value of the impactedByMit property.
             * 
             */
            public boolean isImpactedByMit() {
                return impactedByMit;
            }

            /**
             * Sets the value of the impactedByMit property.
             * 
             */
            public void setImpactedByMit(boolean value) {
                this.impactedByMit = value;
            }

            /**
             * Gets the value of the ctrLowData property.
             * 
             * @return
             *     possible object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public CtrPointDataCommon getCtrLowData() {
                return ctrLowData;
            }

            /**
             * Sets the value of the ctrLowData property.
             * 
             * @param value
             *     allowed object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public void setCtrLowData(CtrPointDataCommon value) {
                this.ctrLowData = value;
            }

            /**
             * Gets the value of the ctrHighData property.
             * 
             * @return
             *     possible object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public CtrPointDataCommon getCtrHighData() {
                return ctrHighData;
            }

            /**
             * Sets the value of the ctrHighData property.
             * 
             * @param value
             *     allowed object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public void setCtrHighData(CtrPointDataCommon value) {
                this.ctrHighData = value;
            }

            /**
             * Gets the value of the ctrSuperHighData property.
             * 
             * @return
             *     possible object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public CtrPointDataCommon getCtrSuperHighData() {
                return ctrSuperHighData;
            }

            /**
             * Sets the value of the ctrSuperHighData property.
             * 
             * @param value
             *     allowed object is
             *     {@link CtrPointDataCommon }
             *     
             */
            public void setCtrSuperHighData(CtrPointDataCommon value) {
                this.ctrSuperHighData = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rerouteId" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}rerouteIdType"/>
     *         &lt;element name="rerouteName" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}rerouteNameType"/>
     *         &lt;element name="modelTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="firstIntervalTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="lastIntervalTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="minutesInInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rerouteId",
        "rerouteName",
        "modelTime",
        "firstIntervalTime",
        "lastIntervalTime",
        "minutesInInterval"
    })
    public static class CtrHead {

        @XmlElement(required = true)
        protected String rerouteId;
        @XmlElement(required = true)
        protected String rerouteName;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar modelTime;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar firstIntervalTime;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar lastIntervalTime;
        @XmlElement(defaultValue = "15")
        protected int minutesInInterval;

        /**
         * Gets the value of the rerouteId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRerouteId() {
            return rerouteId;
        }

        /**
         * Sets the value of the rerouteId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRerouteId(String value) {
            this.rerouteId = value;
        }

        /**
         * Gets the value of the rerouteName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRerouteName() {
            return rerouteName;
        }

        /**
         * Sets the value of the rerouteName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRerouteName(String value) {
            this.rerouteName = value;
        }

        /**
         * Gets the value of the modelTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getModelTime() {
            return modelTime;
        }

        /**
         * Sets the value of the modelTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setModelTime(XMLGregorianCalendar value) {
            this.modelTime = value;
        }

        /**
         * Gets the value of the firstIntervalTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFirstIntervalTime() {
            return firstIntervalTime;
        }

        /**
         * Sets the value of the firstIntervalTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFirstIntervalTime(XMLGregorianCalendar value) {
            this.firstIntervalTime = value;
        }

        /**
         * Gets the value of the lastIntervalTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLastIntervalTime() {
            return lastIntervalTime;
        }

        /**
         * Sets the value of the lastIntervalTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLastIntervalTime(XMLGregorianCalendar value) {
            this.lastIntervalTime = value;
        }

        /**
         * Gets the value of the minutesInInterval property.
         * 
         */
        public int getMinutesInInterval() {
            return minutesInInterval;
        }

        /**
         * Sets the value of the minutesInInterval property.
         * 
         */
        public void setMinutesInInterval(int value) {
            this.minutesInInterval = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ctrCenter" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="centerName" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}airportIdType"/>
     *                   &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="ctrSector" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="sectorType">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="lowsec"/>
     *                                   &lt;enumeration value="highsec"/>
     *                                   &lt;enumeration value="superhisec"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="sectorName">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="10"/>
     *                                   &lt;pattern value="[A-Za-z0-9]*"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="sectorState">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="BASELINE"/>
     *                                   &lt;enumeration value="DYNAMIC"/>
     *                                   &lt;enumeration value="CLOSED"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="sectorsAdded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;sequence>
     *                               &lt;element name="ctrBaselineData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrSectorDataCommon"/>
     *                               &lt;element name="ctrDynamicData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrSectorDataCommon" minOccurs="0"/>
     *                             &lt;/sequence>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ctrCenter"
    })
    public static class CtrSectorList {

        @XmlElement(required = true)
        protected List<RriaTrafficCountsDataType.CtrSectorList.CtrCenter> ctrCenter;

        /**
         * Gets the value of the ctrCenter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ctrCenter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCtrCenter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RriaTrafficCountsDataType.CtrSectorList.CtrCenter }
         * 
         * 
         */
        public List<RriaTrafficCountsDataType.CtrSectorList.CtrCenter> getCtrCenter() {
            if (ctrCenter == null) {
                ctrCenter = new ArrayList<RriaTrafficCountsDataType.CtrSectorList.CtrCenter>();
            }
            return this.ctrCenter;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="centerName" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}airportIdType"/>
         *         &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="ctrSector" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="sectorType">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="lowsec"/>
         *                         &lt;enumeration value="highsec"/>
         *                         &lt;enumeration value="superhisec"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="sectorName">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="10"/>
         *                         &lt;pattern value="[A-Za-z0-9]*"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="sectorState">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="BASELINE"/>
         *                         &lt;enumeration value="DYNAMIC"/>
         *                         &lt;enumeration value="CLOSED"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="sectorsAdded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;sequence>
         *                     &lt;element name="ctrBaselineData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrSectorDataCommon"/>
         *                     &lt;element name="ctrDynamicData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrSectorDataCommon" minOccurs="0"/>
         *                   &lt;/sequence>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "centerName",
            "impactedByReroute",
            "impactedByMit",
            "ctrSector"
        })
        public static class CtrCenter {

            @XmlElement(required = true)
            protected String centerName;
            protected boolean impactedByReroute;
            protected boolean impactedByMit;
            @XmlElement(required = true)
            protected List<RriaTrafficCountsDataType.CtrSectorList.CtrCenter.CtrSector> ctrSector;

            /**
             * Gets the value of the centerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCenterName() {
                return centerName;
            }

            /**
             * Sets the value of the centerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCenterName(String value) {
                this.centerName = value;
            }

            /**
             * Gets the value of the impactedByReroute property.
             * 
             */
            public boolean isImpactedByReroute() {
                return impactedByReroute;
            }

            /**
             * Sets the value of the impactedByReroute property.
             * 
             */
            public void setImpactedByReroute(boolean value) {
                this.impactedByReroute = value;
            }

            /**
             * Gets the value of the impactedByMit property.
             * 
             */
            public boolean isImpactedByMit() {
                return impactedByMit;
            }

            /**
             * Sets the value of the impactedByMit property.
             * 
             */
            public void setImpactedByMit(boolean value) {
                this.impactedByMit = value;
            }

            /**
             * Gets the value of the ctrSector property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ctrSector property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCtrSector().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RriaTrafficCountsDataType.CtrSectorList.CtrCenter.CtrSector }
             * 
             * 
             */
            public List<RriaTrafficCountsDataType.CtrSectorList.CtrCenter.CtrSector> getCtrSector() {
                if (ctrSector == null) {
                    ctrSector = new ArrayList<RriaTrafficCountsDataType.CtrSectorList.CtrCenter.CtrSector>();
                }
                return this.ctrSector;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="sectorType">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="lowsec"/>
             *               &lt;enumeration value="highsec"/>
             *               &lt;enumeration value="superhisec"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="sectorName">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="10"/>
             *               &lt;pattern value="[A-Za-z0-9]*"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="sectorState">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="BASELINE"/>
             *               &lt;enumeration value="DYNAMIC"/>
             *               &lt;enumeration value="CLOSED"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="sectorsAdded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="impactedByReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element name="impactedByMit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;sequence>
             *           &lt;element name="ctrBaselineData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrSectorDataCommon"/>
             *           &lt;element name="ctrDynamicData" type="{urn:us:gov:dot:faa:atm:tfm:tfmrequestreplytypes}ctrSectorDataCommon" minOccurs="0"/>
             *         &lt;/sequence>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "sectorType",
                "sectorName",
                "sectorState",
                "sectorsAdded",
                "impactedByReroute",
                "impactedByMit",
                "ctrBaselineData",
                "ctrDynamicData"
            })
            public static class CtrSector {

                @XmlElement(required = true)
                protected String sectorType;
                @XmlElement(required = true)
                protected String sectorName;
                @XmlElement(required = true)
                protected String sectorState;
                protected String sectorsAdded;
                protected boolean impactedByReroute;
                protected boolean impactedByMit;
                @XmlElement(required = true)
                protected CtrSectorDataCommon ctrBaselineData;
                protected CtrSectorDataCommon ctrDynamicData;

                /**
                 * Gets the value of the sectorType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSectorType() {
                    return sectorType;
                }

                /**
                 * Sets the value of the sectorType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSectorType(String value) {
                    this.sectorType = value;
                }

                /**
                 * Gets the value of the sectorName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSectorName() {
                    return sectorName;
                }

                /**
                 * Sets the value of the sectorName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSectorName(String value) {
                    this.sectorName = value;
                }

                /**
                 * Gets the value of the sectorState property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSectorState() {
                    return sectorState;
                }

                /**
                 * Sets the value of the sectorState property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSectorState(String value) {
                    this.sectorState = value;
                }

                /**
                 * Gets the value of the sectorsAdded property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSectorsAdded() {
                    return sectorsAdded;
                }

                /**
                 * Sets the value of the sectorsAdded property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSectorsAdded(String value) {
                    this.sectorsAdded = value;
                }

                /**
                 * Gets the value of the impactedByReroute property.
                 * 
                 */
                public boolean isImpactedByReroute() {
                    return impactedByReroute;
                }

                /**
                 * Sets the value of the impactedByReroute property.
                 * 
                 */
                public void setImpactedByReroute(boolean value) {
                    this.impactedByReroute = value;
                }

                /**
                 * Gets the value of the impactedByMit property.
                 * 
                 */
                public boolean isImpactedByMit() {
                    return impactedByMit;
                }

                /**
                 * Sets the value of the impactedByMit property.
                 * 
                 */
                public void setImpactedByMit(boolean value) {
                    this.impactedByMit = value;
                }

                /**
                 * Gets the value of the ctrBaselineData property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CtrSectorDataCommon }
                 *     
                 */
                public CtrSectorDataCommon getCtrBaselineData() {
                    return ctrBaselineData;
                }

                /**
                 * Sets the value of the ctrBaselineData property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CtrSectorDataCommon }
                 *     
                 */
                public void setCtrBaselineData(CtrSectorDataCommon value) {
                    this.ctrBaselineData = value;
                }

                /**
                 * Gets the value of the ctrDynamicData property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CtrSectorDataCommon }
                 *     
                 */
                public CtrSectorDataCommon getCtrDynamicData() {
                    return ctrDynamicData;
                }

                /**
                 * Sets the value of the ctrDynamicData property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CtrSectorDataCommon }
                 *     
                 */
                public void setCtrDynamicData(CtrSectorDataCommon value) {
                    this.ctrDynamicData = value;
                }

            }

        }

    }

}
