//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.flowinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import us.gov.dot.faa.atm.tfm.ficommondatatypes.RefreshType;
import us.gov.dot.faa.atm.tfm.tfmdatacoreelements.SensitivityType;
import us.gov.dot.faa.atm.tfm.tfmdatacoreelements.TmiVisibilityDomainType;


/**
 * Defines the possible message attributes associated with a Flow Information message.
 * 
 * <p>Java class for fiMessageAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fiMessageAttributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sensitivity" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}sensitivityType" />
 *       &lt;attribute name="sensReason">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="FM"/>
 *             &lt;enumeration value="FS"/>
 *             &lt;enumeration value="DR"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="visDomain" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}tmiVisibilityDomainType" />
 *       &lt;attribute name="destinationCodes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sourceFacility" use="required" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}facilityIdentifierType" />
 *       &lt;attribute name="sourceTimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="msgType" use="required" type="{urn:us:gov:dot:faa:atm:tfm:flowinformation}messageType" />
 *       &lt;attribute name="refresh" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}refreshType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fiMessageAttributes")
@XmlSeeAlso({
    us.gov.dot.faa.atm.tfm.flowinformation.FiOutputType.FiMessage.class
})
public class FiMessageAttributes {

    @XmlAttribute(name = "sensitivity")
    protected SensitivityType sensitivity;
    @XmlAttribute(name = "sensReason")
    protected String sensReason;
    @XmlAttribute(name = "visDomain")
    protected TmiVisibilityDomainType visDomain;
    @XmlAttribute(name = "destinationCodes")
    protected String destinationCodes;
    @XmlAttribute(name = "sourceFacility", required = true)
    protected String sourceFacility;
    @XmlAttribute(name = "sourceTimeStamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sourceTimeStamp;
    @XmlAttribute(name = "msgType", required = true)
    protected MessageType msgType;
    @XmlAttribute(name = "refresh")
    protected RefreshType refresh;

    /**
     * Gets the value of the sensitivity property.
     * 
     * @return
     *     possible object is
     *     {@link SensitivityType }
     *     
     */
    public SensitivityType getSensitivity() {
        return sensitivity;
    }

    /**
     * Sets the value of the sensitivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SensitivityType }
     *     
     */
    public void setSensitivity(SensitivityType value) {
        this.sensitivity = value;
    }

    /**
     * Gets the value of the sensReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensReason() {
        return sensReason;
    }

    /**
     * Sets the value of the sensReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensReason(String value) {
        this.sensReason = value;
    }

    /**
     * Gets the value of the visDomain property.
     * 
     * @return
     *     possible object is
     *     {@link TmiVisibilityDomainType }
     *     
     */
    public TmiVisibilityDomainType getVisDomain() {
        return visDomain;
    }

    /**
     * Sets the value of the visDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmiVisibilityDomainType }
     *     
     */
    public void setVisDomain(TmiVisibilityDomainType value) {
        this.visDomain = value;
    }

    /**
     * Gets the value of the destinationCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCodes() {
        return destinationCodes;
    }

    /**
     * Sets the value of the destinationCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCodes(String value) {
        this.destinationCodes = value;
    }

    /**
     * Gets the value of the sourceFacility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceFacility() {
        return sourceFacility;
    }

    /**
     * Sets the value of the sourceFacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceFacility(String value) {
        this.sourceFacility = value;
    }

    /**
     * Gets the value of the sourceTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSourceTimeStamp() {
        return sourceTimeStamp;
    }

    /**
     * Sets the value of the sourceTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSourceTimeStamp(XMLGregorianCalendar value) {
        this.sourceTimeStamp = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link MessageType }
     *     
     */
    public MessageType getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageType }
     *     
     */
    public void setMsgType(MessageType value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the refresh property.
     * 
     * @return
     *     possible object is
     *     {@link RefreshType }
     *     
     */
    public RefreshType getRefresh() {
        return refresh;
    }

    /**
     * Sets the value of the refresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefreshType }
     *     
     */
    public void setRefresh(RefreshType value) {
        this.refresh = value;
    }

}
