//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.flowinformation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import us.gov.dot.faa.atm.tfm.ficommondatatypes.OnOffType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.AfpAdvisoryMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.AfpCancelMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.AfpCompressionMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.AirportConfigType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.CtopCancel;
import us.gov.dot.faa.atm.tfm.ficommonmessages.CtopTmiType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.DeicingType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.Fca;
import us.gov.dot.faa.atm.tfm.ficommonmessages.GdpAdvisoryMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.GdpBlanketMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.GdpCancelMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.GdpCompressionMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.GeneralAdvisoryType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.GsAdvisoryMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.GsCancelMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages.RestrictionType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.ControlledFlightType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.EdctOnOffNotificationMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.FadtReqType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.FosFlowInfoOutputType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.FxaSecondaryFilterType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.GenFlightDataType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.MultipleSlotType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.ParamAfpGdpType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.ParamBlanketType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.ParamCompressionType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.ParamDeleteType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.ParamGsType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.RequestorIdType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.RerouteAmendmentResponseType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.RerouteMessageType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.SecondaryFilterDelType;
import us.gov.dot.faa.atm.tfm.ficommonmessages2.SingleSlotType;
import us.gov.dot.faa.atm.tfm.rapttimeline.RaptDataType;


/**
 * Defines the Flow Information message.
 * 
 * <p>Java class for fiOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fiOutputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fiMessage">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:us:gov:dot:faa:atm:tfm:flowinformation}fiMessageAttributes">
 *                 &lt;sequence>
 *                   &lt;element name="destination" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}requestorIdType" minOccurs="0"/>
 *                   &lt;choice>
 *                     &lt;element name="generalAdvisory" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}generalAdvisoryType"/>
 *                     &lt;element name="afpAdvisory" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}afpAdvisoryMessageType"/>
 *                     &lt;element name="afpCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}afpCancelMessageType"/>
 *                     &lt;element name="fadtBcast" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}fadtReqType"/>
 *                     &lt;element name="gdpAdvisory" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gdpAdvisoryMessageType"/>
 *                     &lt;element name="gdpCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gdpCancelMessageType"/>
 *                     &lt;element name="gdpBlanket" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gdpBlanketMessageType"/>
 *                     &lt;element name="gdpCompression" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gdpCompressionMessageType"/>
 *                     &lt;element name="afpCompression" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}afpCompressionMessageType"/>
 *                     &lt;element name="gsAdvisory" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gsAdvisoryMessageType"/>
 *                     &lt;element name="gsCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gsCancelMessageType"/>
 *                     &lt;element name="feaFca" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}fca"/>
 *                     &lt;element name="fxaSecFiltersUpd" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}fxaSecondaryFilterType"/>
 *                     &lt;element name="fxaSecFiltersDel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}secondaryFilterDelType"/>
 *                     &lt;element name="reroute" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}rerouteMessageType"/>
 *                     &lt;element name="ctopDefinition" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}ctopTmiType"/>
 *                     &lt;element name="ctopCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}ctopCancel"/>
 *                     &lt;element name="deicingMessage" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}deicingType"/>
 *                     &lt;element name="restrictionMessage" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}restrictionType"/>
 *                     &lt;element name="airportConfigMessage" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}airportConfigType"/>
 *                     &lt;element name="paramAfpGdpUpdt" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramAfpGdpType"/>
 *                     &lt;element name="paramGsUpdt" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramGsType"/>
 *                     &lt;element name="paramBlanketUpdt" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramBlanketType"/>
 *                     &lt;element name="paramComprUpdt" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramCompressionType"/>
 *                     &lt;element name="paramDelete" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramDeleteType"/>
 *                     &lt;element name="raptTimelineMessage" type="{urn:us:gov:dot:faa:atm:tfm:rapttimeline}raptDataType"/>
 *                     &lt;element name="cdmUpdateData">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;element name="reinstatedFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
 *                               &lt;element name="flightIdChange">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="flightInfo" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
 *                                         &lt;element name="previousFlightId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="diversionCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
 *                               &lt;element name="diversionRecovery" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
 *                               &lt;element name="subStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}edctOnOffNotificationMessageType"/>
 *                               &lt;element name="gdpTermination" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="edctUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
 *                               &lt;element name="dasDelay" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
 *                               &lt;element name="gaapSlotAssignment" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="scsBridgingUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="scsStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}edctOnOffNotificationMessageType"/>
 *                               &lt;element name="scsUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
 *                               &lt;element name="dropoutFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
 *                               &lt;element name="recontrolledFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
 *                               &lt;element name="substitutions" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="holdAllSlots" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="releaseAllSlots" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="timeoutCancelledFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="adaptiveCompressionUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="udpBridgingUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="scopeReduction" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
 *                               &lt;element name="acStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}edctOnOffNotificationMessageType"/>
 *                               &lt;element name="bridgingStatus">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="status" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}onOffType"/>
 *                                         &lt;element name="elementName" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}controlElementNameType"/>
 *                                         &lt;element name="airCarrierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/choice>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="fosData" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}fosFlowInfoOutputType"/>
 *                     &lt;element name="tmiFlightDataList">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="flightData" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}genFlightDataType" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="eramAmendmentStatusUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}rerouteAmendmentResponseType"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fiOutputType", propOrder = {
    "fiMessage"
})
public class FiOutputType {

    @XmlElement(required = true)
    protected FiOutputType.FiMessage fiMessage;

    /**
     * Gets the value of the fiMessage property.
     * 
     * @return
     *     possible object is
     *     {@link FiOutputType.FiMessage }
     *     
     */
    public FiOutputType.FiMessage getFiMessage() {
        return fiMessage;
    }

    /**
     * Sets the value of the fiMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiOutputType.FiMessage }
     *     
     */
    public void setFiMessage(FiOutputType.FiMessage value) {
        this.fiMessage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:us:gov:dot:faa:atm:tfm:flowinformation}fiMessageAttributes">
     *       &lt;sequence>
     *         &lt;element name="destination" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}requestorIdType" minOccurs="0"/>
     *         &lt;choice>
     *           &lt;element name="generalAdvisory" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}generalAdvisoryType"/>
     *           &lt;element name="afpAdvisory" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}afpAdvisoryMessageType"/>
     *           &lt;element name="afpCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}afpCancelMessageType"/>
     *           &lt;element name="fadtBcast" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}fadtReqType"/>
     *           &lt;element name="gdpAdvisory" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gdpAdvisoryMessageType"/>
     *           &lt;element name="gdpCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gdpCancelMessageType"/>
     *           &lt;element name="gdpBlanket" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gdpBlanketMessageType"/>
     *           &lt;element name="gdpCompression" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gdpCompressionMessageType"/>
     *           &lt;element name="afpCompression" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}afpCompressionMessageType"/>
     *           &lt;element name="gsAdvisory" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gsAdvisoryMessageType"/>
     *           &lt;element name="gsCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}gsCancelMessageType"/>
     *           &lt;element name="feaFca" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}fca"/>
     *           &lt;element name="fxaSecFiltersUpd" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}fxaSecondaryFilterType"/>
     *           &lt;element name="fxaSecFiltersDel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}secondaryFilterDelType"/>
     *           &lt;element name="reroute" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}rerouteMessageType"/>
     *           &lt;element name="ctopDefinition" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}ctopTmiType"/>
     *           &lt;element name="ctopCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}ctopCancel"/>
     *           &lt;element name="deicingMessage" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}deicingType"/>
     *           &lt;element name="restrictionMessage" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}restrictionType"/>
     *           &lt;element name="airportConfigMessage" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}airportConfigType"/>
     *           &lt;element name="paramAfpGdpUpdt" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramAfpGdpType"/>
     *           &lt;element name="paramGsUpdt" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramGsType"/>
     *           &lt;element name="paramBlanketUpdt" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramBlanketType"/>
     *           &lt;element name="paramComprUpdt" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramCompressionType"/>
     *           &lt;element name="paramDelete" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}paramDeleteType"/>
     *           &lt;element name="raptTimelineMessage" type="{urn:us:gov:dot:faa:atm:tfm:rapttimeline}raptDataType"/>
     *           &lt;element name="cdmUpdateData">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;choice>
     *                     &lt;element name="reinstatedFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
     *                     &lt;element name="flightIdChange">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="flightInfo" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
     *                               &lt;element name="previousFlightId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="diversionCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
     *                     &lt;element name="diversionRecovery" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
     *                     &lt;element name="subStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}edctOnOffNotificationMessageType"/>
     *                     &lt;element name="gdpTermination" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="edctUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
     *                     &lt;element name="dasDelay" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
     *                     &lt;element name="gaapSlotAssignment" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="scsBridgingUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="scsStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}edctOnOffNotificationMessageType"/>
     *                     &lt;element name="scsUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
     *                     &lt;element name="dropoutFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
     *                     &lt;element name="recontrolledFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
     *                     &lt;element name="substitutions" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="holdAllSlots" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="releaseAllSlots" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="timeoutCancelledFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="adaptiveCompressionUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="udpBridgingUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="scopeReduction" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
     *                     &lt;element name="acStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}edctOnOffNotificationMessageType"/>
     *                     &lt;element name="bridgingStatus">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="status" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}onOffType"/>
     *                               &lt;element name="elementName" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}controlElementNameType"/>
     *                               &lt;element name="airCarrierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/choice>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="fosData" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}fosFlowInfoOutputType"/>
     *           &lt;element name="tmiFlightDataList">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="flightData" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}genFlightDataType" maxOccurs="unbounded"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="eramAmendmentStatusUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}rerouteAmendmentResponseType"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "destination",
        "generalAdvisory",
        "afpAdvisory",
        "afpCancel",
        "fadtBcast",
        "gdpAdvisory",
        "gdpCancel",
        "gdpBlanket",
        "gdpCompression",
        "afpCompression",
        "gsAdvisory",
        "gsCancel",
        "feaFca",
        "fxaSecFiltersUpd",
        "fxaSecFiltersDel",
        "reroute",
        "ctopDefinition",
        "ctopCancel",
        "deicingMessage",
        "restrictionMessage",
        "airportConfigMessage",
        "paramAfpGdpUpdt",
        "paramGsUpdt",
        "paramBlanketUpdt",
        "paramComprUpdt",
        "paramDelete",
        "raptTimelineMessage",
        "cdmUpdateData",
        "fosData",
        "tmiFlightDataList",
        "eramAmendmentStatusUpdate"
    })
    public static class FiMessage
        extends FiMessageAttributes
    {

        protected RequestorIdType destination;
        protected GeneralAdvisoryType generalAdvisory;
        protected AfpAdvisoryMessageType afpAdvisory;
        protected AfpCancelMessageType afpCancel;
        protected FadtReqType fadtBcast;
        protected GdpAdvisoryMessageType gdpAdvisory;
        protected GdpCancelMessageType gdpCancel;
        protected GdpBlanketMessageType gdpBlanket;
        protected GdpCompressionMessageType gdpCompression;
        protected AfpCompressionMessageType afpCompression;
        protected GsAdvisoryMessageType gsAdvisory;
        protected GsCancelMessageType gsCancel;
        protected Fca feaFca;
        protected FxaSecondaryFilterType fxaSecFiltersUpd;
        protected SecondaryFilterDelType fxaSecFiltersDel;
        protected RerouteMessageType reroute;
        protected CtopTmiType ctopDefinition;
        protected CtopCancel ctopCancel;
        protected DeicingType deicingMessage;
        protected RestrictionType restrictionMessage;
        protected AirportConfigType airportConfigMessage;
        protected ParamAfpGdpType paramAfpGdpUpdt;
        protected ParamGsType paramGsUpdt;
        protected ParamBlanketType paramBlanketUpdt;
        protected ParamCompressionType paramComprUpdt;
        protected ParamDeleteType paramDelete;
        protected RaptDataType raptTimelineMessage;
        protected FiOutputType.FiMessage.CdmUpdateData cdmUpdateData;
        protected FosFlowInfoOutputType fosData;
        protected FiOutputType.FiMessage.TmiFlightDataList tmiFlightDataList;
        protected RerouteAmendmentResponseType eramAmendmentStatusUpdate;

        /**
         * Gets the value of the destination property.
         * 
         * @return
         *     possible object is
         *     {@link RequestorIdType }
         *     
         */
        public RequestorIdType getDestination() {
            return destination;
        }

        /**
         * Sets the value of the destination property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestorIdType }
         *     
         */
        public void setDestination(RequestorIdType value) {
            this.destination = value;
        }

        /**
         * Gets the value of the generalAdvisory property.
         * 
         * @return
         *     possible object is
         *     {@link GeneralAdvisoryType }
         *     
         */
        public GeneralAdvisoryType getGeneralAdvisory() {
            return generalAdvisory;
        }

        /**
         * Sets the value of the generalAdvisory property.
         * 
         * @param value
         *     allowed object is
         *     {@link GeneralAdvisoryType }
         *     
         */
        public void setGeneralAdvisory(GeneralAdvisoryType value) {
            this.generalAdvisory = value;
        }

        /**
         * Gets the value of the afpAdvisory property.
         * 
         * @return
         *     possible object is
         *     {@link AfpAdvisoryMessageType }
         *     
         */
        public AfpAdvisoryMessageType getAfpAdvisory() {
            return afpAdvisory;
        }

        /**
         * Sets the value of the afpAdvisory property.
         * 
         * @param value
         *     allowed object is
         *     {@link AfpAdvisoryMessageType }
         *     
         */
        public void setAfpAdvisory(AfpAdvisoryMessageType value) {
            this.afpAdvisory = value;
        }

        /**
         * Gets the value of the afpCancel property.
         * 
         * @return
         *     possible object is
         *     {@link AfpCancelMessageType }
         *     
         */
        public AfpCancelMessageType getAfpCancel() {
            return afpCancel;
        }

        /**
         * Sets the value of the afpCancel property.
         * 
         * @param value
         *     allowed object is
         *     {@link AfpCancelMessageType }
         *     
         */
        public void setAfpCancel(AfpCancelMessageType value) {
            this.afpCancel = value;
        }

        /**
         * Gets the value of the fadtBcast property.
         * 
         * @return
         *     possible object is
         *     {@link FadtReqType }
         *     
         */
        public FadtReqType getFadtBcast() {
            return fadtBcast;
        }

        /**
         * Sets the value of the fadtBcast property.
         * 
         * @param value
         *     allowed object is
         *     {@link FadtReqType }
         *     
         */
        public void setFadtBcast(FadtReqType value) {
            this.fadtBcast = value;
        }

        /**
         * Gets the value of the gdpAdvisory property.
         * 
         * @return
         *     possible object is
         *     {@link GdpAdvisoryMessageType }
         *     
         */
        public GdpAdvisoryMessageType getGdpAdvisory() {
            return gdpAdvisory;
        }

        /**
         * Sets the value of the gdpAdvisory property.
         * 
         * @param value
         *     allowed object is
         *     {@link GdpAdvisoryMessageType }
         *     
         */
        public void setGdpAdvisory(GdpAdvisoryMessageType value) {
            this.gdpAdvisory = value;
        }

        /**
         * Gets the value of the gdpCancel property.
         * 
         * @return
         *     possible object is
         *     {@link GdpCancelMessageType }
         *     
         */
        public GdpCancelMessageType getGdpCancel() {
            return gdpCancel;
        }

        /**
         * Sets the value of the gdpCancel property.
         * 
         * @param value
         *     allowed object is
         *     {@link GdpCancelMessageType }
         *     
         */
        public void setGdpCancel(GdpCancelMessageType value) {
            this.gdpCancel = value;
        }

        /**
         * Gets the value of the gdpBlanket property.
         * 
         * @return
         *     possible object is
         *     {@link GdpBlanketMessageType }
         *     
         */
        public GdpBlanketMessageType getGdpBlanket() {
            return gdpBlanket;
        }

        /**
         * Sets the value of the gdpBlanket property.
         * 
         * @param value
         *     allowed object is
         *     {@link GdpBlanketMessageType }
         *     
         */
        public void setGdpBlanket(GdpBlanketMessageType value) {
            this.gdpBlanket = value;
        }

        /**
         * Gets the value of the gdpCompression property.
         * 
         * @return
         *     possible object is
         *     {@link GdpCompressionMessageType }
         *     
         */
        public GdpCompressionMessageType getGdpCompression() {
            return gdpCompression;
        }

        /**
         * Sets the value of the gdpCompression property.
         * 
         * @param value
         *     allowed object is
         *     {@link GdpCompressionMessageType }
         *     
         */
        public void setGdpCompression(GdpCompressionMessageType value) {
            this.gdpCompression = value;
        }

        /**
         * Gets the value of the afpCompression property.
         * 
         * @return
         *     possible object is
         *     {@link AfpCompressionMessageType }
         *     
         */
        public AfpCompressionMessageType getAfpCompression() {
            return afpCompression;
        }

        /**
         * Sets the value of the afpCompression property.
         * 
         * @param value
         *     allowed object is
         *     {@link AfpCompressionMessageType }
         *     
         */
        public void setAfpCompression(AfpCompressionMessageType value) {
            this.afpCompression = value;
        }

        /**
         * Gets the value of the gsAdvisory property.
         * 
         * @return
         *     possible object is
         *     {@link GsAdvisoryMessageType }
         *     
         */
        public GsAdvisoryMessageType getGsAdvisory() {
            return gsAdvisory;
        }

        /**
         * Sets the value of the gsAdvisory property.
         * 
         * @param value
         *     allowed object is
         *     {@link GsAdvisoryMessageType }
         *     
         */
        public void setGsAdvisory(GsAdvisoryMessageType value) {
            this.gsAdvisory = value;
        }

        /**
         * Gets the value of the gsCancel property.
         * 
         * @return
         *     possible object is
         *     {@link GsCancelMessageType }
         *     
         */
        public GsCancelMessageType getGsCancel() {
            return gsCancel;
        }

        /**
         * Sets the value of the gsCancel property.
         * 
         * @param value
         *     allowed object is
         *     {@link GsCancelMessageType }
         *     
         */
        public void setGsCancel(GsCancelMessageType value) {
            this.gsCancel = value;
        }

        /**
         * Gets the value of the feaFca property.
         * 
         * @return
         *     possible object is
         *     {@link Fca }
         *     
         */
        public Fca getFeaFca() {
            return feaFca;
        }

        /**
         * Sets the value of the feaFca property.
         * 
         * @param value
         *     allowed object is
         *     {@link Fca }
         *     
         */
        public void setFeaFca(Fca value) {
            this.feaFca = value;
        }

        /**
         * Gets the value of the fxaSecFiltersUpd property.
         * 
         * @return
         *     possible object is
         *     {@link FxaSecondaryFilterType }
         *     
         */
        public FxaSecondaryFilterType getFxaSecFiltersUpd() {
            return fxaSecFiltersUpd;
        }

        /**
         * Sets the value of the fxaSecFiltersUpd property.
         * 
         * @param value
         *     allowed object is
         *     {@link FxaSecondaryFilterType }
         *     
         */
        public void setFxaSecFiltersUpd(FxaSecondaryFilterType value) {
            this.fxaSecFiltersUpd = value;
        }

        /**
         * Gets the value of the fxaSecFiltersDel property.
         * 
         * @return
         *     possible object is
         *     {@link SecondaryFilterDelType }
         *     
         */
        public SecondaryFilterDelType getFxaSecFiltersDel() {
            return fxaSecFiltersDel;
        }

        /**
         * Sets the value of the fxaSecFiltersDel property.
         * 
         * @param value
         *     allowed object is
         *     {@link SecondaryFilterDelType }
         *     
         */
        public void setFxaSecFiltersDel(SecondaryFilterDelType value) {
            this.fxaSecFiltersDel = value;
        }

        /**
         * Gets the value of the reroute property.
         * 
         * @return
         *     possible object is
         *     {@link RerouteMessageType }
         *     
         */
        public RerouteMessageType getReroute() {
            return reroute;
        }

        /**
         * Sets the value of the reroute property.
         * 
         * @param value
         *     allowed object is
         *     {@link RerouteMessageType }
         *     
         */
        public void setReroute(RerouteMessageType value) {
            this.reroute = value;
        }

        /**
         * Gets the value of the ctopDefinition property.
         * 
         * @return
         *     possible object is
         *     {@link CtopTmiType }
         *     
         */
        public CtopTmiType getCtopDefinition() {
            return ctopDefinition;
        }

        /**
         * Sets the value of the ctopDefinition property.
         * 
         * @param value
         *     allowed object is
         *     {@link CtopTmiType }
         *     
         */
        public void setCtopDefinition(CtopTmiType value) {
            this.ctopDefinition = value;
        }

        /**
         * Gets the value of the ctopCancel property.
         * 
         * @return
         *     possible object is
         *     {@link CtopCancel }
         *     
         */
        public CtopCancel getCtopCancel() {
            return ctopCancel;
        }

        /**
         * Sets the value of the ctopCancel property.
         * 
         * @param value
         *     allowed object is
         *     {@link CtopCancel }
         *     
         */
        public void setCtopCancel(CtopCancel value) {
            this.ctopCancel = value;
        }

        /**
         * Gets the value of the deicingMessage property.
         * 
         * @return
         *     possible object is
         *     {@link DeicingType }
         *     
         */
        public DeicingType getDeicingMessage() {
            return deicingMessage;
        }

        /**
         * Sets the value of the deicingMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link DeicingType }
         *     
         */
        public void setDeicingMessage(DeicingType value) {
            this.deicingMessage = value;
        }

        /**
         * Gets the value of the restrictionMessage property.
         * 
         * @return
         *     possible object is
         *     {@link RestrictionType }
         *     
         */
        public RestrictionType getRestrictionMessage() {
            return restrictionMessage;
        }

        /**
         * Sets the value of the restrictionMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link RestrictionType }
         *     
         */
        public void setRestrictionMessage(RestrictionType value) {
            this.restrictionMessage = value;
        }

        /**
         * Gets the value of the airportConfigMessage property.
         * 
         * @return
         *     possible object is
         *     {@link AirportConfigType }
         *     
         */
        public AirportConfigType getAirportConfigMessage() {
            return airportConfigMessage;
        }

        /**
         * Sets the value of the airportConfigMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link AirportConfigType }
         *     
         */
        public void setAirportConfigMessage(AirportConfigType value) {
            this.airportConfigMessage = value;
        }

        /**
         * Gets the value of the paramAfpGdpUpdt property.
         * 
         * @return
         *     possible object is
         *     {@link ParamAfpGdpType }
         *     
         */
        public ParamAfpGdpType getParamAfpGdpUpdt() {
            return paramAfpGdpUpdt;
        }

        /**
         * Sets the value of the paramAfpGdpUpdt property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParamAfpGdpType }
         *     
         */
        public void setParamAfpGdpUpdt(ParamAfpGdpType value) {
            this.paramAfpGdpUpdt = value;
        }

        /**
         * Gets the value of the paramGsUpdt property.
         * 
         * @return
         *     possible object is
         *     {@link ParamGsType }
         *     
         */
        public ParamGsType getParamGsUpdt() {
            return paramGsUpdt;
        }

        /**
         * Sets the value of the paramGsUpdt property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParamGsType }
         *     
         */
        public void setParamGsUpdt(ParamGsType value) {
            this.paramGsUpdt = value;
        }

        /**
         * Gets the value of the paramBlanketUpdt property.
         * 
         * @return
         *     possible object is
         *     {@link ParamBlanketType }
         *     
         */
        public ParamBlanketType getParamBlanketUpdt() {
            return paramBlanketUpdt;
        }

        /**
         * Sets the value of the paramBlanketUpdt property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParamBlanketType }
         *     
         */
        public void setParamBlanketUpdt(ParamBlanketType value) {
            this.paramBlanketUpdt = value;
        }

        /**
         * Gets the value of the paramComprUpdt property.
         * 
         * @return
         *     possible object is
         *     {@link ParamCompressionType }
         *     
         */
        public ParamCompressionType getParamComprUpdt() {
            return paramComprUpdt;
        }

        /**
         * Sets the value of the paramComprUpdt property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParamCompressionType }
         *     
         */
        public void setParamComprUpdt(ParamCompressionType value) {
            this.paramComprUpdt = value;
        }

        /**
         * Gets the value of the paramDelete property.
         * 
         * @return
         *     possible object is
         *     {@link ParamDeleteType }
         *     
         */
        public ParamDeleteType getParamDelete() {
            return paramDelete;
        }

        /**
         * Sets the value of the paramDelete property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParamDeleteType }
         *     
         */
        public void setParamDelete(ParamDeleteType value) {
            this.paramDelete = value;
        }

        /**
         * Gets the value of the raptTimelineMessage property.
         * 
         * @return
         *     possible object is
         *     {@link RaptDataType }
         *     
         */
        public RaptDataType getRaptTimelineMessage() {
            return raptTimelineMessage;
        }

        /**
         * Sets the value of the raptTimelineMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link RaptDataType }
         *     
         */
        public void setRaptTimelineMessage(RaptDataType value) {
            this.raptTimelineMessage = value;
        }

        /**
         * Gets the value of the cdmUpdateData property.
         * 
         * @return
         *     possible object is
         *     {@link FiOutputType.FiMessage.CdmUpdateData }
         *     
         */
        public FiOutputType.FiMessage.CdmUpdateData getCdmUpdateData() {
            return cdmUpdateData;
        }

        /**
         * Sets the value of the cdmUpdateData property.
         * 
         * @param value
         *     allowed object is
         *     {@link FiOutputType.FiMessage.CdmUpdateData }
         *     
         */
        public void setCdmUpdateData(FiOutputType.FiMessage.CdmUpdateData value) {
            this.cdmUpdateData = value;
        }

        /**
         * Gets the value of the fosData property.
         * 
         * @return
         *     possible object is
         *     {@link FosFlowInfoOutputType }
         *     
         */
        public FosFlowInfoOutputType getFosData() {
            return fosData;
        }

        /**
         * Sets the value of the fosData property.
         * 
         * @param value
         *     allowed object is
         *     {@link FosFlowInfoOutputType }
         *     
         */
        public void setFosData(FosFlowInfoOutputType value) {
            this.fosData = value;
        }

        /**
         * Gets the value of the tmiFlightDataList property.
         * 
         * @return
         *     possible object is
         *     {@link FiOutputType.FiMessage.TmiFlightDataList }
         *     
         */
        public FiOutputType.FiMessage.TmiFlightDataList getTmiFlightDataList() {
            return tmiFlightDataList;
        }

        /**
         * Sets the value of the tmiFlightDataList property.
         * 
         * @param value
         *     allowed object is
         *     {@link FiOutputType.FiMessage.TmiFlightDataList }
         *     
         */
        public void setTmiFlightDataList(FiOutputType.FiMessage.TmiFlightDataList value) {
            this.tmiFlightDataList = value;
        }

        /**
         * Gets the value of the eramAmendmentStatusUpdate property.
         * 
         * @return
         *     possible object is
         *     {@link RerouteAmendmentResponseType }
         *     
         */
        public RerouteAmendmentResponseType getEramAmendmentStatusUpdate() {
            return eramAmendmentStatusUpdate;
        }

        /**
         * Sets the value of the eramAmendmentStatusUpdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link RerouteAmendmentResponseType }
         *     
         */
        public void setEramAmendmentStatusUpdate(RerouteAmendmentResponseType value) {
            this.eramAmendmentStatusUpdate = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="reinstatedFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
         *         &lt;element name="flightIdChange">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="flightInfo" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
         *                   &lt;element name="previousFlightId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="diversionCancel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
         *         &lt;element name="diversionRecovery" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
         *         &lt;element name="subStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}edctOnOffNotificationMessageType"/>
         *         &lt;element name="gdpTermination" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="edctUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
         *         &lt;element name="dasDelay" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
         *         &lt;element name="gaapSlotAssignment" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="scsBridgingUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="scsStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}edctOnOffNotificationMessageType"/>
         *         &lt;element name="scsUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
         *         &lt;element name="dropoutFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
         *         &lt;element name="recontrolledFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}singleSlotType"/>
         *         &lt;element name="substitutions" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="holdAllSlots" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="releaseAllSlots" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="timeoutCancelledFlight" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="adaptiveCompressionUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="udpBridgingUpdate" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="scopeReduction" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}multipleSlotType"/>
         *         &lt;element name="acStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}edctOnOffNotificationMessageType"/>
         *         &lt;element name="bridgingStatus">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="status" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}onOffType"/>
         *                   &lt;element name="elementName" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}controlElementNameType"/>
         *                   &lt;element name="airCarrierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reinstatedFlight",
            "flightIdChange",
            "diversionCancel",
            "diversionRecovery",
            "subStatus",
            "gdpTermination",
            "edctUpdate",
            "dasDelay",
            "gaapSlotAssignment",
            "scsBridgingUpdate",
            "scsStatus",
            "scsUpdate",
            "dropoutFlight",
            "recontrolledFlight",
            "substitutions",
            "holdAllSlots",
            "releaseAllSlots",
            "timeoutCancelledFlight",
            "adaptiveCompressionUpdate",
            "udpBridgingUpdate",
            "scopeReduction",
            "acStatus",
            "bridgingStatus"
        })
        public static class CdmUpdateData {

            protected SingleSlotType reinstatedFlight;
            protected FiOutputType.FiMessage.CdmUpdateData.FlightIdChange flightIdChange;
            protected ControlledFlightType diversionCancel;
            protected ControlledFlightType diversionRecovery;
            protected EdctOnOffNotificationMessageType subStatus;
            protected MultipleSlotType gdpTermination;
            protected SingleSlotType edctUpdate;
            protected SingleSlotType dasDelay;
            protected MultipleSlotType gaapSlotAssignment;
            protected MultipleSlotType scsBridgingUpdate;
            protected EdctOnOffNotificationMessageType scsStatus;
            protected SingleSlotType scsUpdate;
            protected SingleSlotType dropoutFlight;
            protected SingleSlotType recontrolledFlight;
            protected MultipleSlotType substitutions;
            protected MultipleSlotType holdAllSlots;
            protected MultipleSlotType releaseAllSlots;
            protected MultipleSlotType timeoutCancelledFlight;
            protected MultipleSlotType adaptiveCompressionUpdate;
            protected MultipleSlotType udpBridgingUpdate;
            protected MultipleSlotType scopeReduction;
            protected EdctOnOffNotificationMessageType acStatus;
            protected FiOutputType.FiMessage.CdmUpdateData.BridgingStatus bridgingStatus;

            /**
             * Gets the value of the reinstatedFlight property.
             * 
             * @return
             *     possible object is
             *     {@link SingleSlotType }
             *     
             */
            public SingleSlotType getReinstatedFlight() {
                return reinstatedFlight;
            }

            /**
             * Sets the value of the reinstatedFlight property.
             * 
             * @param value
             *     allowed object is
             *     {@link SingleSlotType }
             *     
             */
            public void setReinstatedFlight(SingleSlotType value) {
                this.reinstatedFlight = value;
            }

            /**
             * Gets the value of the flightIdChange property.
             * 
             * @return
             *     possible object is
             *     {@link FiOutputType.FiMessage.CdmUpdateData.FlightIdChange }
             *     
             */
            public FiOutputType.FiMessage.CdmUpdateData.FlightIdChange getFlightIdChange() {
                return flightIdChange;
            }

            /**
             * Sets the value of the flightIdChange property.
             * 
             * @param value
             *     allowed object is
             *     {@link FiOutputType.FiMessage.CdmUpdateData.FlightIdChange }
             *     
             */
            public void setFlightIdChange(FiOutputType.FiMessage.CdmUpdateData.FlightIdChange value) {
                this.flightIdChange = value;
            }

            /**
             * Gets the value of the diversionCancel property.
             * 
             * @return
             *     possible object is
             *     {@link ControlledFlightType }
             *     
             */
            public ControlledFlightType getDiversionCancel() {
                return diversionCancel;
            }

            /**
             * Sets the value of the diversionCancel property.
             * 
             * @param value
             *     allowed object is
             *     {@link ControlledFlightType }
             *     
             */
            public void setDiversionCancel(ControlledFlightType value) {
                this.diversionCancel = value;
            }

            /**
             * Gets the value of the diversionRecovery property.
             * 
             * @return
             *     possible object is
             *     {@link ControlledFlightType }
             *     
             */
            public ControlledFlightType getDiversionRecovery() {
                return diversionRecovery;
            }

            /**
             * Sets the value of the diversionRecovery property.
             * 
             * @param value
             *     allowed object is
             *     {@link ControlledFlightType }
             *     
             */
            public void setDiversionRecovery(ControlledFlightType value) {
                this.diversionRecovery = value;
            }

            /**
             * Gets the value of the subStatus property.
             * 
             * @return
             *     possible object is
             *     {@link EdctOnOffNotificationMessageType }
             *     
             */
            public EdctOnOffNotificationMessageType getSubStatus() {
                return subStatus;
            }

            /**
             * Sets the value of the subStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link EdctOnOffNotificationMessageType }
             *     
             */
            public void setSubStatus(EdctOnOffNotificationMessageType value) {
                this.subStatus = value;
            }

            /**
             * Gets the value of the gdpTermination property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getGdpTermination() {
                return gdpTermination;
            }

            /**
             * Sets the value of the gdpTermination property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setGdpTermination(MultipleSlotType value) {
                this.gdpTermination = value;
            }

            /**
             * Gets the value of the edctUpdate property.
             * 
             * @return
             *     possible object is
             *     {@link SingleSlotType }
             *     
             */
            public SingleSlotType getEdctUpdate() {
                return edctUpdate;
            }

            /**
             * Sets the value of the edctUpdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link SingleSlotType }
             *     
             */
            public void setEdctUpdate(SingleSlotType value) {
                this.edctUpdate = value;
            }

            /**
             * Gets the value of the dasDelay property.
             * 
             * @return
             *     possible object is
             *     {@link SingleSlotType }
             *     
             */
            public SingleSlotType getDasDelay() {
                return dasDelay;
            }

            /**
             * Sets the value of the dasDelay property.
             * 
             * @param value
             *     allowed object is
             *     {@link SingleSlotType }
             *     
             */
            public void setDasDelay(SingleSlotType value) {
                this.dasDelay = value;
            }

            /**
             * Gets the value of the gaapSlotAssignment property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getGaapSlotAssignment() {
                return gaapSlotAssignment;
            }

            /**
             * Sets the value of the gaapSlotAssignment property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setGaapSlotAssignment(MultipleSlotType value) {
                this.gaapSlotAssignment = value;
            }

            /**
             * Gets the value of the scsBridgingUpdate property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getScsBridgingUpdate() {
                return scsBridgingUpdate;
            }

            /**
             * Sets the value of the scsBridgingUpdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setScsBridgingUpdate(MultipleSlotType value) {
                this.scsBridgingUpdate = value;
            }

            /**
             * Gets the value of the scsStatus property.
             * 
             * @return
             *     possible object is
             *     {@link EdctOnOffNotificationMessageType }
             *     
             */
            public EdctOnOffNotificationMessageType getScsStatus() {
                return scsStatus;
            }

            /**
             * Sets the value of the scsStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link EdctOnOffNotificationMessageType }
             *     
             */
            public void setScsStatus(EdctOnOffNotificationMessageType value) {
                this.scsStatus = value;
            }

            /**
             * Gets the value of the scsUpdate property.
             * 
             * @return
             *     possible object is
             *     {@link SingleSlotType }
             *     
             */
            public SingleSlotType getScsUpdate() {
                return scsUpdate;
            }

            /**
             * Sets the value of the scsUpdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link SingleSlotType }
             *     
             */
            public void setScsUpdate(SingleSlotType value) {
                this.scsUpdate = value;
            }

            /**
             * Gets the value of the dropoutFlight property.
             * 
             * @return
             *     possible object is
             *     {@link SingleSlotType }
             *     
             */
            public SingleSlotType getDropoutFlight() {
                return dropoutFlight;
            }

            /**
             * Sets the value of the dropoutFlight property.
             * 
             * @param value
             *     allowed object is
             *     {@link SingleSlotType }
             *     
             */
            public void setDropoutFlight(SingleSlotType value) {
                this.dropoutFlight = value;
            }

            /**
             * Gets the value of the recontrolledFlight property.
             * 
             * @return
             *     possible object is
             *     {@link SingleSlotType }
             *     
             */
            public SingleSlotType getRecontrolledFlight() {
                return recontrolledFlight;
            }

            /**
             * Sets the value of the recontrolledFlight property.
             * 
             * @param value
             *     allowed object is
             *     {@link SingleSlotType }
             *     
             */
            public void setRecontrolledFlight(SingleSlotType value) {
                this.recontrolledFlight = value;
            }

            /**
             * Gets the value of the substitutions property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getSubstitutions() {
                return substitutions;
            }

            /**
             * Sets the value of the substitutions property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setSubstitutions(MultipleSlotType value) {
                this.substitutions = value;
            }

            /**
             * Gets the value of the holdAllSlots property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getHoldAllSlots() {
                return holdAllSlots;
            }

            /**
             * Sets the value of the holdAllSlots property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setHoldAllSlots(MultipleSlotType value) {
                this.holdAllSlots = value;
            }

            /**
             * Gets the value of the releaseAllSlots property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getReleaseAllSlots() {
                return releaseAllSlots;
            }

            /**
             * Sets the value of the releaseAllSlots property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setReleaseAllSlots(MultipleSlotType value) {
                this.releaseAllSlots = value;
            }

            /**
             * Gets the value of the timeoutCancelledFlight property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getTimeoutCancelledFlight() {
                return timeoutCancelledFlight;
            }

            /**
             * Sets the value of the timeoutCancelledFlight property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setTimeoutCancelledFlight(MultipleSlotType value) {
                this.timeoutCancelledFlight = value;
            }

            /**
             * Gets the value of the adaptiveCompressionUpdate property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getAdaptiveCompressionUpdate() {
                return adaptiveCompressionUpdate;
            }

            /**
             * Sets the value of the adaptiveCompressionUpdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setAdaptiveCompressionUpdate(MultipleSlotType value) {
                this.adaptiveCompressionUpdate = value;
            }

            /**
             * Gets the value of the udpBridgingUpdate property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getUdpBridgingUpdate() {
                return udpBridgingUpdate;
            }

            /**
             * Sets the value of the udpBridgingUpdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setUdpBridgingUpdate(MultipleSlotType value) {
                this.udpBridgingUpdate = value;
            }

            /**
             * Gets the value of the scopeReduction property.
             * 
             * @return
             *     possible object is
             *     {@link MultipleSlotType }
             *     
             */
            public MultipleSlotType getScopeReduction() {
                return scopeReduction;
            }

            /**
             * Sets the value of the scopeReduction property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultipleSlotType }
             *     
             */
            public void setScopeReduction(MultipleSlotType value) {
                this.scopeReduction = value;
            }

            /**
             * Gets the value of the acStatus property.
             * 
             * @return
             *     possible object is
             *     {@link EdctOnOffNotificationMessageType }
             *     
             */
            public EdctOnOffNotificationMessageType getAcStatus() {
                return acStatus;
            }

            /**
             * Sets the value of the acStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link EdctOnOffNotificationMessageType }
             *     
             */
            public void setAcStatus(EdctOnOffNotificationMessageType value) {
                this.acStatus = value;
            }

            /**
             * Gets the value of the bridgingStatus property.
             * 
             * @return
             *     possible object is
             *     {@link FiOutputType.FiMessage.CdmUpdateData.BridgingStatus }
             *     
             */
            public FiOutputType.FiMessage.CdmUpdateData.BridgingStatus getBridgingStatus() {
                return bridgingStatus;
            }

            /**
             * Sets the value of the bridgingStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link FiOutputType.FiMessage.CdmUpdateData.BridgingStatus }
             *     
             */
            public void setBridgingStatus(FiOutputType.FiMessage.CdmUpdateData.BridgingStatus value) {
                this.bridgingStatus = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="status" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}onOffType"/>
             *         &lt;element name="elementName" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}controlElementNameType"/>
             *         &lt;element name="airCarrierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "status",
                "elementName",
                "airCarrierName"
            })
            public static class BridgingStatus {

                @XmlElement(required = true)
                @XmlSchemaType(name = "string")
                protected OnOffType status;
                @XmlElement(required = true)
                protected String elementName;
                @XmlElement(required = true)
                protected String airCarrierName;

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link OnOffType }
                 *     
                 */
                public OnOffType getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link OnOffType }
                 *     
                 */
                public void setStatus(OnOffType value) {
                    this.status = value;
                }

                /**
                 * Gets the value of the elementName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getElementName() {
                    return elementName;
                }

                /**
                 * Sets the value of the elementName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setElementName(String value) {
                    this.elementName = value;
                }

                /**
                 * Gets the value of the airCarrierName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAirCarrierName() {
                    return airCarrierName;
                }

                /**
                 * Sets the value of the airCarrierName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAirCarrierName(String value) {
                    this.airCarrierName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="flightInfo" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}controlledFlightType"/>
             *         &lt;element name="previousFlightId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "flightInfo",
                "previousFlightId"
            })
            public static class FlightIdChange {

                @XmlElement(required = true)
                protected ControlledFlightType flightInfo;
                @XmlElement(required = true)
                protected String previousFlightId;

                /**
                 * Gets the value of the flightInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ControlledFlightType }
                 *     
                 */
                public ControlledFlightType getFlightInfo() {
                    return flightInfo;
                }

                /**
                 * Sets the value of the flightInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ControlledFlightType }
                 *     
                 */
                public void setFlightInfo(ControlledFlightType value) {
                    this.flightInfo = value;
                }

                /**
                 * Gets the value of the previousFlightId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPreviousFlightId() {
                    return previousFlightId;
                }

                /**
                 * Sets the value of the previousFlightId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPreviousFlightId(String value) {
                    this.previousFlightId = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="flightData" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages2}genFlightDataType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "flightData"
        })
        public static class TmiFlightDataList {

            @XmlElement(required = true)
            protected List<GenFlightDataType> flightData;

            /**
             * Gets the value of the flightData property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the flightData property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFlightData().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GenFlightDataType }
             * 
             * 
             */
            public List<GenFlightDataType> getFlightData() {
                if (flightData == null) {
                    flightData = new ArrayList<GenFlightDataType>();
                }
                return this.flightData;
            }

        }

    }

}
