//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.base._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import aero.fixm.flight._3.UnitBoundaryType;


/**
 * 
 *             Reference to an Air Traffic Control organization of any type: unit, sector, etc. 
 *             
 *          
 * 
 * <p>Java class for AtcUnitReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AtcUnitReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="delegated" type="{http://www.fixm.aero/base/3.0}DelegatedUnitIndicatorType" />
 *       &lt;attribute name="sectorIdentifier" type="{http://www.fixm.aero/base/3.0}FreeTextType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AtcUnitReferenceType")
@XmlSeeAlso({
    IdentifiedUnitReferenceType.class,
    UnknownUnitReferenceType.class,
    UnitBoundaryType.class
})
public abstract class AtcUnitReferenceType {

    @XmlAttribute(name = "delegated")
    protected DelegatedUnitIndicatorType delegated;
    @XmlAttribute(name = "sectorIdentifier")
    protected String sectorIdentifier;

    /**
     * Gets the value of the delegated property.
     * 
     * @return
     *     possible object is
     *     {@link DelegatedUnitIndicatorType }
     *     
     */
    public DelegatedUnitIndicatorType getDelegated() {
        return delegated;
    }

    /**
     * Sets the value of the delegated property.
     * 
     * @param value
     *     allowed object is
     *     {@link DelegatedUnitIndicatorType }
     *     
     */
    public void setDelegated(DelegatedUnitIndicatorType value) {
        this.delegated = value;
    }

    /**
     * Gets the value of the sectorIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectorIdentifier() {
        return sectorIdentifier;
    }

    /**
     * Sets the value of the sectorIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectorIdentifier(String value) {
        this.sectorIdentifier = value;
    }

}
