//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.base._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             Reference to an airport stand that an aircraft can arrive at, depart from, or traverse 
 *             during arrival, departure, or surface movement. 
 *          
 * 
 * <p>Java class for StandPositionAndTimeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StandPositionAndTimeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="standTime" type="{http://www.fixm.aero/base/3.0}ExtendedMultiTimeType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="standName" type="{http://www.fixm.aero/foundation/3.0}StandNameType" />
 *       &lt;attribute name="terminalName" type="{http://www.fixm.aero/foundation/3.0}TerminalNameType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandPositionAndTimeType", propOrder = {
    "standTime"
})
public class StandPositionAndTimeType {

    protected ExtendedMultiTimeType standTime;
    @XmlAttribute(name = "standName")
    protected String standName;
    @XmlAttribute(name = "terminalName")
    protected String terminalName;

    /**
     * Gets the value of the standTime property.
     * 
     * @return
     *     possible object is
     *     {@link ExtendedMultiTimeType }
     *     
     */
    public ExtendedMultiTimeType getStandTime() {
        return standTime;
    }

    /**
     * Sets the value of the standTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtendedMultiTimeType }
     *     
     */
    public void setStandTime(ExtendedMultiTimeType value) {
        this.standTime = value;
    }

    /**
     * Gets the value of the standName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandName() {
        return standName;
    }

    /**
     * Sets the value of the standName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandName(String value) {
        this.standName = value;
    }

    /**
     * Gets the value of the terminalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalName() {
        return terminalName;
    }

    /**
     * Sets the value of the terminalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalName(String value) {
        this.terminalName = value;
    }

}
