//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.faa.nas._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import aero.fixm.base._3.ReportedTimeType;


/**
 * 
 *             Container for : 
 *             Airspace Entry Time - Earliest 
 *             Airspace Entry Time - Initial 
 *             Airspace Entry Time - Original 
 *             Airspace Entry Time - Traffic Flow Management System Estimated 
 *          
 * 
 * <p>Java class for AirspaceEntryTimeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AirspaceEntryTimeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="earliest" type="{http://www.fixm.aero/base/3.0}ReportedTimeType" minOccurs="0"/>
 *         &lt;element name="initial" type="{http://www.fixm.aero/base/3.0}ReportedTimeType" minOccurs="0"/>
 *         &lt;element name="original" type="{http://www.fixm.aero/base/3.0}ReportedTimeType" minOccurs="0"/>
 *         &lt;element name="slotSubstitution" type="{http://www.faa.aero/nas/3.1}AirspaceAcceptableSlotSubstitutionType" minOccurs="0"/>
 *         &lt;element name="tfmsEstimated" type="{http://www.fixm.aero/base/3.0}ReportedTimeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirspaceEntryTimeType", propOrder = {
    "earliest",
    "initial",
    "original",
    "slotSubstitution",
    "tfmsEstimated"
})
public class AirspaceEntryTimeType {

    protected ReportedTimeType earliest;
    protected ReportedTimeType initial;
    protected ReportedTimeType original;
    protected AirspaceAcceptableSlotSubstitutionType slotSubstitution;
    protected ReportedTimeType tfmsEstimated;

    /**
     * Gets the value of the earliest property.
     * 
     * @return
     *     possible object is
     *     {@link ReportedTimeType }
     *     
     */
    public ReportedTimeType getEarliest() {
        return earliest;
    }

    /**
     * Sets the value of the earliest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportedTimeType }
     *     
     */
    public void setEarliest(ReportedTimeType value) {
        this.earliest = value;
    }

    /**
     * Gets the value of the initial property.
     * 
     * @return
     *     possible object is
     *     {@link ReportedTimeType }
     *     
     */
    public ReportedTimeType getInitial() {
        return initial;
    }

    /**
     * Sets the value of the initial property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportedTimeType }
     *     
     */
    public void setInitial(ReportedTimeType value) {
        this.initial = value;
    }

    /**
     * Gets the value of the original property.
     * 
     * @return
     *     possible object is
     *     {@link ReportedTimeType }
     *     
     */
    public ReportedTimeType getOriginal() {
        return original;
    }

    /**
     * Sets the value of the original property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportedTimeType }
     *     
     */
    public void setOriginal(ReportedTimeType value) {
        this.original = value;
    }

    /**
     * Gets the value of the slotSubstitution property.
     * 
     * @return
     *     possible object is
     *     {@link AirspaceAcceptableSlotSubstitutionType }
     *     
     */
    public AirspaceAcceptableSlotSubstitutionType getSlotSubstitution() {
        return slotSubstitution;
    }

    /**
     * Sets the value of the slotSubstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirspaceAcceptableSlotSubstitutionType }
     *     
     */
    public void setSlotSubstitution(AirspaceAcceptableSlotSubstitutionType value) {
        this.slotSubstitution = value;
    }

    /**
     * Gets the value of the tfmsEstimated property.
     * 
     * @return
     *     possible object is
     *     {@link ReportedTimeType }
     *     
     */
    public ReportedTimeType getTfmsEstimated() {
        return tfmsEstimated;
    }

    /**
     * Sets the value of the tfmsEstimated property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportedTimeType }
     *     
     */
    public void setTfmsEstimated(ReportedTimeType value) {
        this.tfmsEstimated = value;
    }

}
