//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.faa.nas._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import aero.fixm.flight._3.RankedTrajectoryType;


/**
 * 
 *             .Traffic Flow Management Collaborative Trajectory Options Program Information: A 
 *             container for a Traffic Flow Management Collaborative Trajectory Options Program 
 *             pertinent information for a flight. 
 *             .Trajectory Option Set: A container for information pertinent to a single trajectory 
 *             option for a flight. 
 *          
 * 
 * <p>Java class for NasTrajectoryOptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NasTrajectoryOptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/flight/3.0}RankedTrajectoryType">
 *       &lt;sequence>
 *         &lt;element name="constrainedAirspaceEntry" type="{http://www.faa.aero/nas/3.1}ConstrainedAirspaceEntryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ctopIdentifier">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.fixm.aero/base/3.0}FreeTextType">
 *             &lt;pattern value="CTP\d{3}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ctopName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.fixm.aero/base/3.0}FreeTextType">
 *             &lt;maxLength value="30"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="manualOverride" type="{http://www.faa.aero/nas/3.1}ManualOverrideIndicatorType" />
 *       &lt;attribute name="minimumNotificationMinutes" type="{http://www.fixm.aero/base/3.0}CountType" />
 *       &lt;attribute name="relativeCost" type="{http://www.fixm.aero/base/3.0}CountType" />
 *       &lt;attribute name="tosSequenceNumber" type="{http://www.fixm.aero/base/3.0}CountType" />
 *       &lt;attribute name="totalCost" type="{http://www.fixm.aero/base/3.0}CountType" />
 *       &lt;attribute name="validEndTime" type="{http://www.fixm.aero/foundation/3.0}TimeType" />
 *       &lt;attribute name="validStartTime" type="{http://www.fixm.aero/foundation/3.0}TimeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NasTrajectoryOptionType", propOrder = {
    "constrainedAirspaceEntry"
})
public class NasTrajectoryOptionType
    extends RankedTrajectoryType
{

    protected List<ConstrainedAirspaceEntryType> constrainedAirspaceEntry;
    @XmlAttribute(name = "ctopIdentifier")
    protected String ctopIdentifier;
    @XmlAttribute(name = "ctopName")
    protected String ctopName;
    @XmlAttribute(name = "manualOverride")
    protected ManualOverrideIndicatorType manualOverride;
    @XmlAttribute(name = "minimumNotificationMinutes")
    protected Integer minimumNotificationMinutes;
    @XmlAttribute(name = "relativeCost")
    protected Integer relativeCost;
    @XmlAttribute(name = "tosSequenceNumber")
    protected Integer tosSequenceNumber;
    @XmlAttribute(name = "totalCost")
    protected Integer totalCost;
    @XmlAttribute(name = "validEndTime")
    protected XMLGregorianCalendar validEndTime;
    @XmlAttribute(name = "validStartTime")
    protected XMLGregorianCalendar validStartTime;

    /**
     * Gets the value of the constrainedAirspaceEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constrainedAirspaceEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstrainedAirspaceEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConstrainedAirspaceEntryType }
     * 
     * 
     */
    public List<ConstrainedAirspaceEntryType> getConstrainedAirspaceEntry() {
        if (constrainedAirspaceEntry == null) {
            constrainedAirspaceEntry = new ArrayList<ConstrainedAirspaceEntryType>();
        }
        return this.constrainedAirspaceEntry;
    }

    /**
     * Gets the value of the ctopIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtopIdentifier() {
        return ctopIdentifier;
    }

    /**
     * Sets the value of the ctopIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtopIdentifier(String value) {
        this.ctopIdentifier = value;
    }

    /**
     * Gets the value of the ctopName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtopName() {
        return ctopName;
    }

    /**
     * Sets the value of the ctopName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtopName(String value) {
        this.ctopName = value;
    }

    /**
     * Gets the value of the manualOverride property.
     * 
     * @return
     *     possible object is
     *     {@link ManualOverrideIndicatorType }
     *     
     */
    public ManualOverrideIndicatorType getManualOverride() {
        return manualOverride;
    }

    /**
     * Sets the value of the manualOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManualOverrideIndicatorType }
     *     
     */
    public void setManualOverride(ManualOverrideIndicatorType value) {
        this.manualOverride = value;
    }

    /**
     * Gets the value of the minimumNotificationMinutes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinimumNotificationMinutes() {
        return minimumNotificationMinutes;
    }

    /**
     * Sets the value of the minimumNotificationMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinimumNotificationMinutes(Integer value) {
        this.minimumNotificationMinutes = value;
    }

    /**
     * Gets the value of the relativeCost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRelativeCost() {
        return relativeCost;
    }

    /**
     * Sets the value of the relativeCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRelativeCost(Integer value) {
        this.relativeCost = value;
    }

    /**
     * Gets the value of the tosSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTosSequenceNumber() {
        return tosSequenceNumber;
    }

    /**
     * Sets the value of the tosSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTosSequenceNumber(Integer value) {
        this.tosSequenceNumber = value;
    }

    /**
     * Gets the value of the totalCost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalCost() {
        return totalCost;
    }

    /**
     * Sets the value of the totalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalCost(Integer value) {
        this.totalCost = value;
    }

    /**
     * Gets the value of the validEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidEndTime() {
        return validEndTime;
    }

    /**
     * Sets the value of the validEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidEndTime(XMLGregorianCalendar value) {
        this.validEndTime = value;
    }

    /**
     * Gets the value of the validStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidStartTime() {
        return validStartTime;
    }

    /**
     * Sets the value of the validStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidStartTime(XMLGregorianCalendar value) {
        this.validStartTime = value;
    }

}
