//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.ficommonmessages2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rerouteWarningType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rerouteWarningType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MERGE_ANGLE"/>
 *     &lt;enumeration value="AMD_FREQUENCY"/>
 *     &lt;enumeration value="MODIFIED_FLT_DATA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rerouteWarningType")
@XmlEnum
public enum RerouteWarningType {


    /**
     * 
     *         This enumerated value indicates a merge angle warning.
     *      
     * 
     */
    MERGE_ANGLE,

    /**
     * 
     *         This enumated value indicates a violation of the cool-down period 
     *         before sending another amendment request.
     *      
     * 
     */
    AMD_FREQUENCY,

    /**
     * 
     *         This enumated value indicates a warning the flight contains modified 
     *         data that has not been displayed yet.
     *      
     * 
     */
    MODIFIED_FLT_DATA;

    public String value() {
        return name();
    }

    public static RerouteWarningType fromValue(String v) {
        return valueOf(v);
    }

}
