//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbrogationReasonCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AbrogationReasonCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TFL"/>
 *     &lt;enumeration value="ROUTE"/>
 *     &lt;enumeration value="CANCELLATION"/>
 *     &lt;enumeration value="DELAY"/>
 *     &lt;enumeration value="HOLD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AbrogationReasonCodeType")
@XmlEnum
public enum AbrogationReasonCodeType {

    TFL,
    ROUTE,
    CANCELLATION,
    DELAY,
    HOLD;

    public String value() {
        return name();
    }

    public static AbrogationReasonCodeType fromValue(String v) {
        return valueOf(v);
    }

}
