//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import aero.faa.nas._3.NasRoutePointType;
import aero.fixm.base._3.AirTrafficTypeType;
import aero.fixm.base._3.FlightRulesType;
import aero.fixm.base._3.SignificantPointType;


/**
 * 
 *             An abstract route point containing basic shared data between RoutePoint and ExpandedRoutePoint. 
 *             
 *          
 * 
 * <p>Java class for AbstractRoutePointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractRoutePointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="point" type="{http://www.fixm.aero/base/3.0}SignificantPointType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="airTrafficType" type="{http://www.fixm.aero/base/3.0}AirTrafficTypeType" />
 *       &lt;attribute name="clearanceLimit" type="{http://www.fixm.aero/flight/3.0}ClearanceLimitIndicatorType" />
 *       &lt;attribute name="delayAtPoint" type="{http://www.fixm.aero/foundation/3.0}DurationType" />
 *       &lt;attribute name="flightRules" type="{http://www.fixm.aero/base/3.0}FlightRulesType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractRoutePointType", propOrder = {
    "point"
})
@XmlSeeAlso({
    RoutePointType.class,
    ExpandedRoutePointType.class,
    NasRoutePointType.class
})
public abstract class AbstractRoutePointType {

    protected SignificantPointType point;
    @XmlAttribute(name = "airTrafficType")
    protected AirTrafficTypeType airTrafficType;
    @XmlAttribute(name = "clearanceLimit")
    protected ClearanceLimitIndicatorType clearanceLimit;
    @XmlAttribute(name = "delayAtPoint")
    protected Duration delayAtPoint;
    @XmlAttribute(name = "flightRules")
    protected FlightRulesType flightRules;

    /**
     * Gets the value of the point property.
     * 
     * @return
     *     possible object is
     *     {@link SignificantPointType }
     *     
     */
    public SignificantPointType getPoint() {
        return point;
    }

    /**
     * Sets the value of the point property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignificantPointType }
     *     
     */
    public void setPoint(SignificantPointType value) {
        this.point = value;
    }

    /**
     * Gets the value of the airTrafficType property.
     * 
     * @return
     *     possible object is
     *     {@link AirTrafficTypeType }
     *     
     */
    public AirTrafficTypeType getAirTrafficType() {
        return airTrafficType;
    }

    /**
     * Sets the value of the airTrafficType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirTrafficTypeType }
     *     
     */
    public void setAirTrafficType(AirTrafficTypeType value) {
        this.airTrafficType = value;
    }

    /**
     * Gets the value of the clearanceLimit property.
     * 
     * @return
     *     possible object is
     *     {@link ClearanceLimitIndicatorType }
     *     
     */
    public ClearanceLimitIndicatorType getClearanceLimit() {
        return clearanceLimit;
    }

    /**
     * Sets the value of the clearanceLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearanceLimitIndicatorType }
     *     
     */
    public void setClearanceLimit(ClearanceLimitIndicatorType value) {
        this.clearanceLimit = value;
    }

    /**
     * Gets the value of the delayAtPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDelayAtPoint() {
        return delayAtPoint;
    }

    /**
     * Sets the value of the delayAtPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDelayAtPoint(Duration value) {
        this.delayAtPoint = value;
    }

    /**
     * Gets the value of the flightRules property.
     * 
     * @return
     *     possible object is
     *     {@link FlightRulesType }
     *     
     */
    public FlightRulesType getFlightRules() {
        return flightRules;
    }

    /**
     * Sets the value of the flightRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightRulesType }
     *     
     */
    public void setFlightRules(FlightRulesType value) {
        this.flightRules = value;
    }

}
