//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import aero.faa.nas._3.NasAircraftType;
import aero.fixm.base._3.FeatureType;


/**
 * 
 *             This is a main aircraft class that contains all the information about the aircraft. 
 *             
 *          
 * 
 * <p>Java class for AircraftType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AircraftType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/base/3.0}FeatureType">
 *       &lt;sequence>
 *         &lt;element name="aircraftType" type="{http://www.fixm.aero/flight/3.0}AircraftTypeType" minOccurs="0"/>
 *         &lt;element name="capabilities" type="{http://www.fixm.aero/flight/3.0}AircraftCapabilitiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="aircraftAddress" type="{http://www.fixm.aero/flight/3.0}AircraftAddressType" />
 *       &lt;attribute name="aircraftColours" type="{http://www.fixm.aero/base/3.0}FreeTextType" />
 *       &lt;attribute name="aircraftPerformance" type="{http://www.fixm.aero/flight/3.0}AircraftPerformanceCategoryType" />
 *       &lt;attribute name="aircraftQuantity" type="{http://www.fixm.aero/base/3.0}CountType" />
 *       &lt;attribute name="engineType" type="{http://www.fixm.aero/flight/3.0}EngineTypeType" />
 *       &lt;attribute name="registration" type="{http://www.fixm.aero/flight/3.0}AircraftRegistrationType" />
 *       &lt;attribute name="wakeTurbulence" type="{http://www.fixm.aero/flight/3.0}WakeTurbulenceCategoryType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AircraftType", propOrder = {
    "aircraftType",
    "capabilities"
})
@XmlSeeAlso({
    NasAircraftType.class
})
public class AircraftType
    extends FeatureType
{

    protected AircraftTypeType aircraftType;
    protected AircraftCapabilitiesType capabilities;
    @XmlAttribute(name = "aircraftAddress")
    protected String aircraftAddress;
    @XmlAttribute(name = "aircraftColours")
    protected String aircraftColours;
    @XmlAttribute(name = "aircraftPerformance")
    protected AircraftPerformanceCategoryType aircraftPerformance;
    @XmlAttribute(name = "aircraftQuantity")
    protected Integer aircraftQuantity;
    @XmlAttribute(name = "engineType")
    protected EngineTypeType engineType;
    @XmlAttribute(name = "registration")
    protected String registration;
    @XmlAttribute(name = "wakeTurbulence")
    protected WakeTurbulenceCategoryType wakeTurbulence;

    /**
     * Gets the value of the aircraftType property.
     * 
     * @return
     *     possible object is
     *     {@link AircraftTypeType }
     *     
     */
    public AircraftTypeType getAircraftType() {
        return aircraftType;
    }

    /**
     * Sets the value of the aircraftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AircraftTypeType }
     *     
     */
    public void setAircraftType(AircraftTypeType value) {
        this.aircraftType = value;
    }

    /**
     * Gets the value of the capabilities property.
     * 
     * @return
     *     possible object is
     *     {@link AircraftCapabilitiesType }
     *     
     */
    public AircraftCapabilitiesType getCapabilities() {
        return capabilities;
    }

    /**
     * Sets the value of the capabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link AircraftCapabilitiesType }
     *     
     */
    public void setCapabilities(AircraftCapabilitiesType value) {
        this.capabilities = value;
    }

    /**
     * Gets the value of the aircraftAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftAddress() {
        return aircraftAddress;
    }

    /**
     * Sets the value of the aircraftAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftAddress(String value) {
        this.aircraftAddress = value;
    }

    /**
     * Gets the value of the aircraftColours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftColours() {
        return aircraftColours;
    }

    /**
     * Sets the value of the aircraftColours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftColours(String value) {
        this.aircraftColours = value;
    }

    /**
     * Gets the value of the aircraftPerformance property.
     * 
     * @return
     *     possible object is
     *     {@link AircraftPerformanceCategoryType }
     *     
     */
    public AircraftPerformanceCategoryType getAircraftPerformance() {
        return aircraftPerformance;
    }

    /**
     * Sets the value of the aircraftPerformance property.
     * 
     * @param value
     *     allowed object is
     *     {@link AircraftPerformanceCategoryType }
     *     
     */
    public void setAircraftPerformance(AircraftPerformanceCategoryType value) {
        this.aircraftPerformance = value;
    }

    /**
     * Gets the value of the aircraftQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAircraftQuantity() {
        return aircraftQuantity;
    }

    /**
     * Sets the value of the aircraftQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAircraftQuantity(Integer value) {
        this.aircraftQuantity = value;
    }

    /**
     * Gets the value of the engineType property.
     * 
     * @return
     *     possible object is
     *     {@link EngineTypeType }
     *     
     */
    public EngineTypeType getEngineType() {
        return engineType;
    }

    /**
     * Sets the value of the engineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EngineTypeType }
     *     
     */
    public void setEngineType(EngineTypeType value) {
        this.engineType = value;
    }

    /**
     * Gets the value of the registration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistration() {
        return registration;
    }

    /**
     * Sets the value of the registration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistration(String value) {
        this.registration = value;
    }

    /**
     * Gets the value of the wakeTurbulence property.
     * 
     * @return
     *     possible object is
     *     {@link WakeTurbulenceCategoryType }
     *     
     */
    public WakeTurbulenceCategoryType getWakeTurbulence() {
        return wakeTurbulence;
    }

    /**
     * Sets the value of the wakeTurbulence property.
     * 
     * @param value
     *     allowed object is
     *     {@link WakeTurbulenceCategoryType }
     *     
     */
    public void setWakeTurbulence(WakeTurbulenceCategoryType value) {
        this.wakeTurbulence = value;
    }

}
