//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import aero.fixm.base._3.AirspeedChoiceType;
import aero.fixm.base._3.AltitudeChoiceType;
import aero.fixm.base._3.LateralOfftrackType;
import aero.fixm.base._3.SignificantPointType;


/**
 * 
 *             Abstract Boundary Crossing contains shared data between the BoundaryCrossingProposed 
 *             and BoundaryCrossingCoordinated classes. 
 *          
 * 
 * <p>Java class for BoundaryCrossingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BoundaryCrossingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="altitude" type="{http://www.fixm.aero/base/3.0}AltitudeChoiceType" minOccurs="0"/>
 *         &lt;element name="altitudeInTransition" type="{http://www.fixm.aero/flight/3.0}AltitudeInTransitionType" minOccurs="0"/>
 *         &lt;element name="crossingPoint" type="{http://www.fixm.aero/base/3.0}SignificantPointType" minOccurs="0"/>
 *         &lt;element name="crossingSpeed" type="{http://www.fixm.aero/base/3.0}AirspeedChoiceType" minOccurs="0"/>
 *         &lt;element name="offtrack" type="{http://www.fixm.aero/base/3.0}LateralOfftrackType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="crossingTime" type="{http://www.fixm.aero/foundation/3.0}TimeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundaryCrossingType", propOrder = {
    "altitude",
    "altitudeInTransition",
    "crossingPoint",
    "crossingSpeed",
    "offtrack"
})
public class BoundaryCrossingType {

    protected AltitudeChoiceType altitude;
    protected AltitudeInTransitionType altitudeInTransition;
    protected SignificantPointType crossingPoint;
    protected AirspeedChoiceType crossingSpeed;
    protected LateralOfftrackType offtrack;
    @XmlAttribute(name = "crossingTime")
    protected XMLGregorianCalendar crossingTime;

    /**
     * Gets the value of the altitude property.
     * 
     * @return
     *     possible object is
     *     {@link AltitudeChoiceType }
     *     
     */
    public AltitudeChoiceType getAltitude() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltitudeChoiceType }
     *     
     */
    public void setAltitude(AltitudeChoiceType value) {
        this.altitude = value;
    }

    /**
     * Gets the value of the altitudeInTransition property.
     * 
     * @return
     *     possible object is
     *     {@link AltitudeInTransitionType }
     *     
     */
    public AltitudeInTransitionType getAltitudeInTransition() {
        return altitudeInTransition;
    }

    /**
     * Sets the value of the altitudeInTransition property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltitudeInTransitionType }
     *     
     */
    public void setAltitudeInTransition(AltitudeInTransitionType value) {
        this.altitudeInTransition = value;
    }

    /**
     * Gets the value of the crossingPoint property.
     * 
     * @return
     *     possible object is
     *     {@link SignificantPointType }
     *     
     */
    public SignificantPointType getCrossingPoint() {
        return crossingPoint;
    }

    /**
     * Sets the value of the crossingPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignificantPointType }
     *     
     */
    public void setCrossingPoint(SignificantPointType value) {
        this.crossingPoint = value;
    }

    /**
     * Gets the value of the crossingSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link AirspeedChoiceType }
     *     
     */
    public AirspeedChoiceType getCrossingSpeed() {
        return crossingSpeed;
    }

    /**
     * Sets the value of the crossingSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirspeedChoiceType }
     *     
     */
    public void setCrossingSpeed(AirspeedChoiceType value) {
        this.crossingSpeed = value;
    }

    /**
     * Gets the value of the offtrack property.
     * 
     * @return
     *     possible object is
     *     {@link LateralOfftrackType }
     *     
     */
    public LateralOfftrackType getOfftrack() {
        return offtrack;
    }

    /**
     * Sets the value of the offtrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link LateralOfftrackType }
     *     
     */
    public void setOfftrack(LateralOfftrackType value) {
        this.offtrack = value;
    }

    /**
     * Gets the value of the crossingTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCrossingTime() {
        return crossingTime;
    }

    /**
     * Sets the value of the crossingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCrossingTime(XMLGregorianCalendar value) {
        this.crossingTime = value;
    }

}
