//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import aero.fixm.foundation._3.AltitudeType;


/**
 * 
 *             .Change Cruise Climb: The parameters of a cruise climb executed at the associated 
 *             significant point. It contains the following parameters: 1. the speed to be maintained 
 *             during cruise climb; 2. either the minimum and maximum levels defining the layer 
 *             to be occupied during cruise climb, or the level above which cruise climb is planned. 
 *             
 *             .Route-Change Cruise Climb: The parameters of a cruise climb executed at the associated 
 *             significant point. 
 *          
 * 
 * <p>Java class for ClimbToLevelConstraintType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClimbToLevelConstraintType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/flight/3.0}RouteConstraintOrPreferenceType">
 *       &lt;sequence>
 *         &lt;element name="climbToLevel" type="{http://www.fixm.aero/foundation/3.0}AltitudeType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="altitudeQualification" type="{http://www.fixm.aero/flight/3.0}AltitudeQualifierType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClimbToLevelConstraintType", propOrder = {
    "climbToLevel"
})
public class ClimbToLevelConstraintType
    extends RouteConstraintOrPreferenceType
{

    protected AltitudeType climbToLevel;
    @XmlAttribute(name = "altitudeQualification")
    protected AltitudeQualifierType altitudeQualification;

    /**
     * Gets the value of the climbToLevel property.
     * 
     * @return
     *     possible object is
     *     {@link AltitudeType }
     *     
     */
    public AltitudeType getClimbToLevel() {
        return climbToLevel;
    }

    /**
     * Sets the value of the climbToLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltitudeType }
     *     
     */
    public void setClimbToLevel(AltitudeType value) {
        this.climbToLevel = value;
    }

    /**
     * Gets the value of the altitudeQualification property.
     * 
     * @return
     *     possible object is
     *     {@link AltitudeQualifierType }
     *     
     */
    public AltitudeQualifierType getAltitudeQualification() {
        return altitudeQualification;
    }

    /**
     * Sets the value of the altitudeQualification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltitudeQualifierType }
     *     
     */
    public void setAltitudeQualification(AltitudeQualifierType value) {
        this.altitudeQualification = value;
    }

}
