//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConstraintOrPreferenceCategoryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConstraintOrPreferenceCategoryType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EXECUTIVE_CONTROL"/>
 *     &lt;enumeration value="CONTROLLER_TACTICAL_PLANNING"/>
 *     &lt;enumeration value="NETWORK_STRATEGIC"/>
 *     &lt;enumeration value="OPERATOR_CONSTRAINT"/>
 *     &lt;enumeration value="FLIGHT_PLAN_EXPECTATION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ConstraintOrPreferenceCategoryType")
@XmlEnum
public enum ConstraintOrPreferenceCategoryType {

    EXECUTIVE_CONTROL,
    CONTROLLER_TACTICAL_PLANNING,
    NETWORK_STRATEGIC,
    OPERATOR_CONSTRAINT,
    FLIGHT_PLAN_EXPECTATION;

    public String value() {
        return name();
    }

    public static ConstraintOrPreferenceCategoryType fromValue(String v) {
        return valueOf(v);
    }

}
