//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             .Declaration Text: Consignor: The consignor's statement indicating the dangerous 
 *             goods have been packaged and handled according to regulations. 
 *             .Declaration Text: Shipper: This shipper's statement indicating the dangerous goods 
 *             have been packaged and handled according to regulations. 
 *             .Declaration Text: Compliance: The warning message for not complying with the regulations. 
 *             
 *          
 * 
 * <p>Java class for DeclarationTextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeclarationTextType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="compliance" type="{http://www.fixm.aero/base/3.0}FreeTextType" />
 *       &lt;attribute name="consignor" type="{http://www.fixm.aero/base/3.0}FreeTextType" />
 *       &lt;attribute name="shipper" type="{http://www.fixm.aero/base/3.0}FreeTextType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeclarationTextType")
public class DeclarationTextType {

    @XmlAttribute(name = "compliance")
    protected String compliance;
    @XmlAttribute(name = "consignor")
    protected String consignor;
    @XmlAttribute(name = "shipper")
    protected String shipper;

    /**
     * Gets the value of the compliance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompliance() {
        return compliance;
    }

    /**
     * Sets the value of the compliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompliance(String value) {
        this.compliance = value;
    }

    /**
     * Gets the value of the consignor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsignor() {
        return consignor;
    }

    /**
     * Sets the value of the consignor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsignor(String value) {
        this.consignor = value;
    }

    /**
     * Gets the value of the shipper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipper() {
        return shipper;
    }

    /**
     * Sets the value of the shipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipper(String value) {
        this.shipper = value;
    }

}
