//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NonStandardCoordinationReasonType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NonStandardCoordinationReasonType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LATE_ACTIVATION"/>
 *     &lt;enumeration value="LATERAL_DEVIATION"/>
 *     &lt;enumeration value="LATE_REVISION"/>
 *     &lt;enumeration value="NON_STANDARD_TFL"/>
 *     &lt;enumeration value="NON_STANDARD_EQUIPMENT"/>
 *     &lt;enumeration value="NON_STANDARD_SSR_CODE"/>
 *     &lt;enumeration value="TRANSITION_POINT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NonStandardCoordinationReasonType")
@XmlEnum
public enum NonStandardCoordinationReasonType {

    LATE_ACTIVATION,
    LATERAL_DEVIATION,
    LATE_REVISION,
    NON_STANDARD_TFL,
    NON_STANDARD_EQUIPMENT,
    NON_STANDARD_SSR_CODE,
    TRANSITION_POINT;

    public String value() {
        return name();
    }

    public static NonStandardCoordinationReasonType fromValue(String v) {
        return valueOf(v);
    }

}
