//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import aero.fixm.base._3.LateralOfftrackType;
import aero.fixm.base._3.VerticalRangeType;


/**
 * 
 *             Provides a vertical, lateral or temporal range to a 4D point when clearances are 
 *             provided in the form of: 
 *              
 *     block altitude clearances
 *     offsets for deviations due to weather
 *     assigned speed ranges
 *             .Point Range: Provides a vertical, lateral or temporal range to a 4D point when clearances 
 *             are provided in the form of:block altitude clearancesoffsets for deviations due to 
 *             weatherassigned speed ranges 
 *          
 * 
 * <p>Java class for PointRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointRangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lateralRange" type="{http://www.fixm.aero/base/3.0}LateralOfftrackType" minOccurs="0"/>
 *         &lt;element name="temporalRange" type="{http://www.fixm.aero/flight/3.0}TemporalRangeType" minOccurs="0"/>
 *         &lt;element name="verticalRange" type="{http://www.fixm.aero/base/3.0}VerticalRangeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointRangeType", propOrder = {
    "lateralRange",
    "temporalRange",
    "verticalRange"
})
public class PointRangeType {

    protected LateralOfftrackType lateralRange;
    protected TemporalRangeType temporalRange;
    protected VerticalRangeType verticalRange;

    /**
     * Gets the value of the lateralRange property.
     * 
     * @return
     *     possible object is
     *     {@link LateralOfftrackType }
     *     
     */
    public LateralOfftrackType getLateralRange() {
        return lateralRange;
    }

    /**
     * Sets the value of the lateralRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link LateralOfftrackType }
     *     
     */
    public void setLateralRange(LateralOfftrackType value) {
        this.lateralRange = value;
    }

    /**
     * Gets the value of the temporalRange property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalRangeType }
     *     
     */
    public TemporalRangeType getTemporalRange() {
        return temporalRange;
    }

    /**
     * Sets the value of the temporalRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalRangeType }
     *     
     */
    public void setTemporalRange(TemporalRangeType value) {
        this.temporalRange = value;
    }

    /**
     * Gets the value of the verticalRange property.
     * 
     * @return
     *     possible object is
     *     {@link VerticalRangeType }
     *     
     */
    public VerticalRangeType getVerticalRange() {
        return verticalRange;
    }

    /**
     * Sets the value of the verticalRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerticalRangeType }
     *     
     */
    public void setVerticalRange(VerticalRangeType value) {
        this.verticalRange = value;
    }

}
