//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import aero.fixm.foundation._3.AltitudeType;
import aero.fixm.foundation._3.GeographicLocationType;


/**
 * 
 *             .4D Point: Identifies the location, altitude and time of a trajectory point. 
 *          
 * 
 * <p>Java class for Point4DType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Point4DType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/foundation/3.0}GeographicLocationType">
 *       &lt;sequence>
 *         &lt;element name="altitude" type="{http://www.fixm.aero/foundation/3.0}AltitudeType" minOccurs="0"/>
 *         &lt;element name="pointRange" type="{http://www.fixm.aero/flight/3.0}PointRangeType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="time" type="{http://www.fixm.aero/foundation/3.0}TimeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Point4DType", propOrder = {
    "altitude",
    "pointRange"
})
public class Point4DType
    extends GeographicLocationType
{

    protected AltitudeType altitude;
    protected PointRangeType pointRange;
    @XmlAttribute(name = "time")
    protected XMLGregorianCalendar time;

    /**
     * Gets the value of the altitude property.
     * 
     * @return
     *     possible object is
     *     {@link AltitudeType }
     *     
     */
    public AltitudeType getAltitude() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltitudeType }
     *     
     */
    public void setAltitude(AltitudeType value) {
        this.altitude = value;
    }

    /**
     * Gets the value of the pointRange property.
     * 
     * @return
     *     possible object is
     *     {@link PointRangeType }
     *     
     */
    public PointRangeType getPointRange() {
        return pointRange;
    }

    /**
     * Sets the value of the pointRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointRangeType }
     *     
     */
    public void setPointRange(PointRangeType value) {
        this.pointRange = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

}
