//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.flight._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             A constraint that is applicable to a route. Can be any of the several defined constraints. 
 *             
 *          
 * 
 * <p>Java class for RouteConstraintOrPreferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteConstraintOrPreferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="constraintType" type="{http://www.fixm.aero/flight/3.0}ConstraintOrPreferenceCategoryType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteConstraintOrPreferenceType")
@XmlSeeAlso({
    SpeedConstraintType.class,
    ClimbToLevelConstraintType.class,
    TimeConstraintType.class,
    LevelConstraintType.class
})
public abstract class RouteConstraintOrPreferenceType {

    @XmlAttribute(name = "constraintType")
    protected ConstraintOrPreferenceCategoryType constraintType;

    /**
     * Gets the value of the constraintType property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintOrPreferenceCategoryType }
     *     
     */
    public ConstraintOrPreferenceCategoryType getConstraintType() {
        return constraintType;
    }

    /**
     * Sets the value of the constraintType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintOrPreferenceCategoryType }
     *     
     */
    public void setConstraintType(ConstraintOrPreferenceCategoryType value) {
        this.constraintType = value;
    }

}
