//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.ficommonmessages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import us.gov.dot.faa.atm.tfm.ficommondatatypes.DelayInfoType;
import us.gov.dot.faa.atm.tfm.ficommondatatypes.ElementTypeType;
import us.gov.dot.faa.atm.tfm.ficommondatatypes.FacilityListType;
import us.gov.dot.faa.atm.tfm.ficommondatatypes.FlightInfoListType;
import us.gov.dot.faa.atm.tfm.ficommondatatypes.TimePeriodType;


/**
 * Message type for GS advisory.
 * 
 * <p>Java class for gsAdvisoryMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gsAdvisoryMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="advisoryTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="updateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="tmiStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}tmiStatusType"/>
 *         &lt;element name="currentDelays" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}delayInfoType" minOccurs="0"/>
 *         &lt;element name="anticipatedDelays" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}delayInfoType" minOccurs="0"/>
 *         &lt;element name="airportId" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}airportIdType"/>
 *         &lt;element name="center" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}centerIdType"/>
 *         &lt;element name="pgmExpTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="elementType" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}elementTypeType"/>
 *         &lt;element name="adlTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="groundStopPeriod" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}timePeriodType"/>
 *         &lt;element name="cumulativeProgramPeriod" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}timePeriodType"/>
 *         &lt;element name="flightInclusionsList" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}flightInfoListType" minOccurs="0"/>
 *         &lt;element name="departureFacilitiesIncludedList" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}facilityListType" minOccurs="0"/>
 *         &lt;element name="aircraftTypesIncluded" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}includedAircraftType"/>
 *         &lt;element name="exemptDepartureFacilitiesList" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}facilityListType" minOccurs="0"/>
 *         &lt;element name="exemptFlightList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="flightId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="impactingCondition" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}reasonType"/>
 *         &lt;element name="advisoryValidPeriod" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}timePeriodType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gsAdvisoryMessageType", propOrder = {
    "advisoryTypeName",
    "updateTime",
    "tmiStatus",
    "currentDelays",
    "anticipatedDelays",
    "airportId",
    "center",
    "pgmExpTime",
    "elementType",
    "adlTime",
    "groundStopPeriod",
    "cumulativeProgramPeriod",
    "flightInclusionsList",
    "departureFacilitiesIncludedList",
    "aircraftTypesIncluded",
    "exemptDepartureFacilitiesList",
    "exemptFlightList",
    "impactingCondition",
    "advisoryValidPeriod"
})
public class GsAdvisoryMessageType {

    @XmlElement(required = true)
    protected String advisoryTypeName;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updateTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TmiStatusType tmiStatus;
    protected DelayInfoType currentDelays;
    protected DelayInfoType anticipatedDelays;
    @XmlElement(required = true)
    protected String airportId;
    @XmlElement(required = true)
    protected String center;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar pgmExpTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ElementTypeType elementType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar adlTime;
    @XmlElement(required = true)
    protected TimePeriodType groundStopPeriod;
    @XmlElement(required = true)
    protected TimePeriodType cumulativeProgramPeriod;
    protected FlightInfoListType flightInclusionsList;
    protected FacilityListType departureFacilitiesIncludedList;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected IncludedAircraftType aircraftTypesIncluded;
    protected FacilityListType exemptDepartureFacilitiesList;
    protected GsAdvisoryMessageType.ExemptFlightList exemptFlightList;
    @XmlElement(required = true)
    protected String impactingCondition;
    @XmlElement(required = true)
    protected TimePeriodType advisoryValidPeriod;

    /**
     * Gets the value of the advisoryTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvisoryTypeName() {
        return advisoryTypeName;
    }

    /**
     * Sets the value of the advisoryTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvisoryTypeName(String value) {
        this.advisoryTypeName = value;
    }

    /**
     * Gets the value of the updateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateTime() {
        return updateTime;
    }

    /**
     * Sets the value of the updateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateTime(XMLGregorianCalendar value) {
        this.updateTime = value;
    }

    /**
     * Gets the value of the tmiStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TmiStatusType }
     *     
     */
    public TmiStatusType getTmiStatus() {
        return tmiStatus;
    }

    /**
     * Sets the value of the tmiStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmiStatusType }
     *     
     */
    public void setTmiStatus(TmiStatusType value) {
        this.tmiStatus = value;
    }

    /**
     * Gets the value of the currentDelays property.
     * 
     * @return
     *     possible object is
     *     {@link DelayInfoType }
     *     
     */
    public DelayInfoType getCurrentDelays() {
        return currentDelays;
    }

    /**
     * Sets the value of the currentDelays property.
     * 
     * @param value
     *     allowed object is
     *     {@link DelayInfoType }
     *     
     */
    public void setCurrentDelays(DelayInfoType value) {
        this.currentDelays = value;
    }

    /**
     * Gets the value of the anticipatedDelays property.
     * 
     * @return
     *     possible object is
     *     {@link DelayInfoType }
     *     
     */
    public DelayInfoType getAnticipatedDelays() {
        return anticipatedDelays;
    }

    /**
     * Sets the value of the anticipatedDelays property.
     * 
     * @param value
     *     allowed object is
     *     {@link DelayInfoType }
     *     
     */
    public void setAnticipatedDelays(DelayInfoType value) {
        this.anticipatedDelays = value;
    }

    /**
     * Gets the value of the airportId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirportId() {
        return airportId;
    }

    /**
     * Sets the value of the airportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirportId(String value) {
        this.airportId = value;
    }

    /**
     * Gets the value of the center property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCenter() {
        return center;
    }

    /**
     * Sets the value of the center property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCenter(String value) {
        this.center = value;
    }

    /**
     * Gets the value of the pgmExpTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPgmExpTime() {
        return pgmExpTime;
    }

    /**
     * Sets the value of the pgmExpTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPgmExpTime(XMLGregorianCalendar value) {
        this.pgmExpTime = value;
    }

    /**
     * Gets the value of the elementType property.
     * 
     * @return
     *     possible object is
     *     {@link ElementTypeType }
     *     
     */
    public ElementTypeType getElementType() {
        return elementType;
    }

    /**
     * Sets the value of the elementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementTypeType }
     *     
     */
    public void setElementType(ElementTypeType value) {
        this.elementType = value;
    }

    /**
     * Gets the value of the adlTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAdlTime() {
        return adlTime;
    }

    /**
     * Sets the value of the adlTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAdlTime(XMLGregorianCalendar value) {
        this.adlTime = value;
    }

    /**
     * Gets the value of the groundStopPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodType }
     *     
     */
    public TimePeriodType getGroundStopPeriod() {
        return groundStopPeriod;
    }

    /**
     * Sets the value of the groundStopPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodType }
     *     
     */
    public void setGroundStopPeriod(TimePeriodType value) {
        this.groundStopPeriod = value;
    }

    /**
     * Gets the value of the cumulativeProgramPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodType }
     *     
     */
    public TimePeriodType getCumulativeProgramPeriod() {
        return cumulativeProgramPeriod;
    }

    /**
     * Sets the value of the cumulativeProgramPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodType }
     *     
     */
    public void setCumulativeProgramPeriod(TimePeriodType value) {
        this.cumulativeProgramPeriod = value;
    }

    /**
     * Gets the value of the flightInclusionsList property.
     * 
     * @return
     *     possible object is
     *     {@link FlightInfoListType }
     *     
     */
    public FlightInfoListType getFlightInclusionsList() {
        return flightInclusionsList;
    }

    /**
     * Sets the value of the flightInclusionsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightInfoListType }
     *     
     */
    public void setFlightInclusionsList(FlightInfoListType value) {
        this.flightInclusionsList = value;
    }

    /**
     * Gets the value of the departureFacilitiesIncludedList property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityListType }
     *     
     */
    public FacilityListType getDepartureFacilitiesIncludedList() {
        return departureFacilitiesIncludedList;
    }

    /**
     * Sets the value of the departureFacilitiesIncludedList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityListType }
     *     
     */
    public void setDepartureFacilitiesIncludedList(FacilityListType value) {
        this.departureFacilitiesIncludedList = value;
    }

    /**
     * Gets the value of the aircraftTypesIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link IncludedAircraftType }
     *     
     */
    public IncludedAircraftType getAircraftTypesIncluded() {
        return aircraftTypesIncluded;
    }

    /**
     * Sets the value of the aircraftTypesIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludedAircraftType }
     *     
     */
    public void setAircraftTypesIncluded(IncludedAircraftType value) {
        this.aircraftTypesIncluded = value;
    }

    /**
     * Gets the value of the exemptDepartureFacilitiesList property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityListType }
     *     
     */
    public FacilityListType getExemptDepartureFacilitiesList() {
        return exemptDepartureFacilitiesList;
    }

    /**
     * Sets the value of the exemptDepartureFacilitiesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityListType }
     *     
     */
    public void setExemptDepartureFacilitiesList(FacilityListType value) {
        this.exemptDepartureFacilitiesList = value;
    }

    /**
     * Gets the value of the exemptFlightList property.
     * 
     * @return
     *     possible object is
     *     {@link GsAdvisoryMessageType.ExemptFlightList }
     *     
     */
    public GsAdvisoryMessageType.ExemptFlightList getExemptFlightList() {
        return exemptFlightList;
    }

    /**
     * Sets the value of the exemptFlightList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GsAdvisoryMessageType.ExemptFlightList }
     *     
     */
    public void setExemptFlightList(GsAdvisoryMessageType.ExemptFlightList value) {
        this.exemptFlightList = value;
    }

    /**
     * Gets the value of the impactingCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpactingCondition() {
        return impactingCondition;
    }

    /**
     * Sets the value of the impactingCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpactingCondition(String value) {
        this.impactingCondition = value;
    }

    /**
     * Gets the value of the advisoryValidPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodType }
     *     
     */
    public TimePeriodType getAdvisoryValidPeriod() {
        return advisoryValidPeriod;
    }

    /**
     * Sets the value of the advisoryValidPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodType }
     *     
     */
    public void setAdvisoryValidPeriod(TimePeriodType value) {
        this.advisoryValidPeriod = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="flightId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flightId"
    })
    public static class ExemptFlightList {

        @XmlElement(required = true)
        protected List<String> flightId;

        /**
         * Gets the value of the flightId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flightId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlightId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getFlightId() {
            if (flightId == null) {
                flightId = new ArrayList<String>();
            }
            return this.flightId;
        }

    }

}
