//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.ficommonmessages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Route data as defined in ICAO 4444 field 15c
 * 
 * <p>Java class for icaoRouteCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="icaoRouteCType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="96">
 *         &lt;element name="filedFix">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:us:gov:dot:faa:atm:tfm:ficommonmessages>icaoFixType">
 *                 &lt;attribute name="cruiseSpeed" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}icaoSpdType" />
 *                 &lt;attribute name="cruiseLevel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}icaoAltType" />
 *                 &lt;attribute name="cruiseLevel2" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}icaoAltType" />
 *                 &lt;attribute name="cruiseClimbInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="cruiseClimbPlusInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="fixNameInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="latLongInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="fixRadDistInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="filedRoute">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="2"/>
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="specialUseInd">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="VFR"/>
 *               &lt;enumeration value="IFR"/>
 *               &lt;enumeration value="DCT"/>
 *               &lt;enumeration value="T"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unknown">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="2"/>
 *               &lt;maxLength value="28"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "icaoRouteCType", propOrder = {
    "filedFixOrFiledRouteOrSpecialUseInd"
})
public class IcaoRouteCType {

    @XmlElementRefs({
        @XmlElementRef(name = "filedFix", namespace = "urn:us:gov:dot:faa:atm:tfm:ficommonmessages", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "filedRoute", namespace = "urn:us:gov:dot:faa:atm:tfm:ficommonmessages", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unknown", namespace = "urn:us:gov:dot:faa:atm:tfm:ficommonmessages", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "specialUseInd", namespace = "urn:us:gov:dot:faa:atm:tfm:ficommonmessages", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> filedFixOrFiledRouteOrSpecialUseInd;

    /**
     * Gets the value of the filedFixOrFiledRouteOrSpecialUseInd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filedFixOrFiledRouteOrSpecialUseInd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFiledFixOrFiledRouteOrSpecialUseInd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link IcaoRouteCType.FiledFix }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getFiledFixOrFiledRouteOrSpecialUseInd() {
        if (filedFixOrFiledRouteOrSpecialUseInd == null) {
            filedFixOrFiledRouteOrSpecialUseInd = new ArrayList<JAXBElement<?>>();
        }
        return this.filedFixOrFiledRouteOrSpecialUseInd;
    }


    /**
     * Extends the ICAO Fix type.
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:us:gov:dot:faa:atm:tfm:ficommonmessages>icaoFixType">
     *       &lt;attribute name="cruiseSpeed" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}icaoSpdType" />
     *       &lt;attribute name="cruiseLevel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}icaoAltType" />
     *       &lt;attribute name="cruiseLevel2" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}icaoAltType" />
     *       &lt;attribute name="cruiseClimbInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="cruiseClimbPlusInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="fixNameInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="latLongInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="fixRadDistInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FiledFix {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "cruiseSpeed")
        protected String cruiseSpeed;
        @XmlAttribute(name = "cruiseLevel")
        protected String cruiseLevel;
        @XmlAttribute(name = "cruiseLevel2")
        protected String cruiseLevel2;
        @XmlAttribute(name = "cruiseClimbInd")
        protected Boolean cruiseClimbInd;
        @XmlAttribute(name = "cruiseClimbPlusInd")
        protected Boolean cruiseClimbPlusInd;
        @XmlAttribute(name = "fixNameInd")
        protected Boolean fixNameInd;
        @XmlAttribute(name = "latLongInd")
        protected Boolean latLongInd;
        @XmlAttribute(name = "fixRadDistInd")
        protected Boolean fixRadDistInd;

        /**
         * Fix name format as defined in ICAO 4444 field 15 c3, c4, and c6
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the cruiseSpeed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCruiseSpeed() {
            return cruiseSpeed;
        }

        /**
         * Sets the value of the cruiseSpeed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCruiseSpeed(String value) {
            this.cruiseSpeed = value;
        }

        /**
         * Gets the value of the cruiseLevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCruiseLevel() {
            return cruiseLevel;
        }

        /**
         * Sets the value of the cruiseLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCruiseLevel(String value) {
            this.cruiseLevel = value;
        }

        /**
         * Gets the value of the cruiseLevel2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCruiseLevel2() {
            return cruiseLevel2;
        }

        /**
         * Sets the value of the cruiseLevel2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCruiseLevel2(String value) {
            this.cruiseLevel2 = value;
        }

        /**
         * Gets the value of the cruiseClimbInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isCruiseClimbInd() {
            return cruiseClimbInd;
        }

        /**
         * Sets the value of the cruiseClimbInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCruiseClimbInd(Boolean value) {
            this.cruiseClimbInd = value;
        }

        /**
         * Gets the value of the cruiseClimbPlusInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isCruiseClimbPlusInd() {
            return cruiseClimbPlusInd;
        }

        /**
         * Sets the value of the cruiseClimbPlusInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCruiseClimbPlusInd(Boolean value) {
            this.cruiseClimbPlusInd = value;
        }

        /**
         * Gets the value of the fixNameInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isFixNameInd() {
            return fixNameInd;
        }

        /**
         * Sets the value of the fixNameInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setFixNameInd(Boolean value) {
            this.fixNameInd = value;
        }

        /**
         * Gets the value of the latLongInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLatLongInd() {
            return latLongInd;
        }

        /**
         * Sets the value of the latLongInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLatLongInd(Boolean value) {
            this.latLongInd = value;
        }

        /**
         * Gets the value of the fixRadDistInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isFixRadDistInd() {
            return fixRadDistInd;
        }

        /**
         * Sets the value of the fixRadDistInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setFixRadDistInd(Boolean value) {
            this.fixRadDistInd = value;
        }

    }

}
