//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.ficommonmessages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for includedAircraftType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="includedAircraftType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="JET DEP ONLY"/>
 *     &lt;enumeration value="PROP DEP ONLY"/>
 *     &lt;enumeration value="JET AND PROP ONLY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "includedAircraftType")
@XmlEnum
public enum IncludedAircraftType {

    @XmlEnumValue("JET DEP ONLY")
    JET_DEP_ONLY("JET DEP ONLY"),
    @XmlEnumValue("PROP DEP ONLY")
    PROP_DEP_ONLY("PROP DEP ONLY"),
    @XmlEnumValue("JET AND PROP ONLY")
    JET_AND_PROP_ONLY("JET AND PROP ONLY");
    private final String value;

    IncludedAircraftType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IncludedAircraftType fromValue(String v) {
        for (IncludedAircraftType c: IncludedAircraftType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
