//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:us:gov:dot:faa:atm:tfm:ficommonmessages", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package us.gov.dot.faa.atm.tfm.ficommonmessages;
