//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.ficommonmessages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Primary filter type.
 * 
 * <p>Java class for primaryFilterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="primaryFilterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conditions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="anyConditions" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}anyAllConditionsType" minOccurs="0"/>
 *                   &lt;element name="allConditions" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}anyAllConditionsType" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "primaryFilterType", propOrder = {
    "conditions"
})
@XmlSeeAlso({
    SecondaryFilterType.class
})
public class PrimaryFilterType {

    @XmlElement(required = true)
    protected PrimaryFilterType.Conditions conditions;

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryFilterType.Conditions }
     *     
     */
    public PrimaryFilterType.Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryFilterType.Conditions }
     *     
     */
    public void setConditions(PrimaryFilterType.Conditions value) {
        this.conditions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="anyConditions" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}anyAllConditionsType" minOccurs="0"/>
     *         &lt;element name="allConditions" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}anyAllConditionsType" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Conditions {

        protected AnyAllConditionsType anyConditions;
        protected AnyAllConditionsType allConditions;

        /**
         * Gets the value of the anyConditions property.
         * 
         * @return
         *     possible object is
         *     {@link AnyAllConditionsType }
         *     
         */
        public AnyAllConditionsType getAnyConditions() {
            return anyConditions;
        }

        /**
         * Sets the value of the anyConditions property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyAllConditionsType }
         *     
         */
        public void setAnyConditions(AnyAllConditionsType value) {
            this.anyConditions = value;
        }

        /**
         * Gets the value of the allConditions property.
         * 
         * @return
         *     possible object is
         *     {@link AnyAllConditionsType }
         *     
         */
        public AnyAllConditionsType getAllConditions() {
            return allConditions;
        }

        /**
         * Sets the value of the allConditions property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyAllConditionsType }
         *     
         */
        public void setAllConditions(AnyAllConditionsType value) {
            this.allConditions = value;
        }

    }

}
