//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.ficommonmessages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import us.gov.dot.faa.atm.tfm.ficommondatatypes.AffectedFlightStatus;
import us.gov.dot.faa.atm.tfm.ficommondatatypes.TmiStatusType;
import us.gov.dot.faa.atm.tfm.tfmdatacoreelements.TmiVisibilityDomainType;


/**
 * The reroute general data.
 * 
 * <p>Java class for rerouteGeneralDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rerouteGeneralDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rerouteId" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}rerouteIdType"/>
 *         &lt;element name="rerouteName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[a-zA-Z0-9_\-:]{2,64}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rerouteStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ACTIVE"/>
 *               &lt;enumeration value="PLANNED"/>
 *               &lt;enumeration value="EXPIRED"/>
 *               &lt;enumeration value="DELETED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tmiId" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}tmiIdType" minOccurs="0"/>
 *         &lt;element name="tmiStatus" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}tmiStatusType"/>
 *         &lt;element name="rerouteDataDomain" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}tmiVisibilityDomainType"/>
 *         &lt;element name="lastUpdateDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="originalCreateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="site">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[a-zA-Z0-9]{1,8}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rerouteWorkstationId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\w{0,8}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rerouteAirborne" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}affectedFlightStatus"/>
 *         &lt;element name="applyProtectedSegments" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="protectedSegment" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="monitorReroute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="drawFixes" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}drawFlag"/>
 *         &lt;element name="drawNavaids" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}drawFlag"/>
 *         &lt;element name="drawRerouteLabel" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}drawFlag"/>
 *         &lt;element name="drawRerouteByDefault" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}drawFlag"/>
 *         &lt;element name="colorId" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}colorIdType"/>
 *         &lt;element name="rerouteTimeType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ETA"/>
 *               &lt;enumeration value="ETD"/>
 *               &lt;enumeration value="FCA"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rerouteStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="rerouteEndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="fcaName" type="{urn:us:gov:dot:faa:atm:tfm:ficommondatatypes}fcaNameType" minOccurs="0"/>
 *         &lt;element name="fcaStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="fcaEndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="cancelDroppedFlights" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ALL"/>
 *               &lt;enumeration value="NOT_AIRBORNE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="canceledRerouteList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="canceledRerouteId" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}rerouteIdType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tmiIdHistory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rerouteGeneralDataType", propOrder = {
    "rerouteId",
    "rerouteName",
    "rerouteStatus",
    "tmiId",
    "tmiStatus",
    "rerouteDataDomain",
    "lastUpdateDateTime",
    "originalCreateTime",
    "site",
    "rerouteWorkstationId",
    "rerouteAirborne",
    "applyProtectedSegments",
    "protectedSegment",
    "monitorReroute",
    "drawFixes",
    "drawNavaids",
    "drawRerouteLabel",
    "drawRerouteByDefault",
    "colorId",
    "rerouteTimeType",
    "rerouteStartTime",
    "rerouteEndTime",
    "fcaName",
    "fcaStartTime",
    "fcaEndTime",
    "cancelDroppedFlights",
    "canceledRerouteList",
    "tmiIdHistory"
})
public class RerouteGeneralDataType {

    @XmlElement(required = true)
    protected String rerouteId;
    @XmlElement(required = true)
    protected String rerouteName;
    @XmlElement(required = true)
    protected String rerouteStatus;
    protected String tmiId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TmiStatusType tmiStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TmiVisibilityDomainType rerouteDataDomain;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdateDateTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar originalCreateTime;
    @XmlElement(required = true)
    protected String site;
    @XmlElement(required = true)
    protected String rerouteWorkstationId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected AffectedFlightStatus rerouteAirborne;
    protected boolean applyProtectedSegments;
    @XmlElement(required = true)
    protected Object protectedSegment;
    protected boolean monitorReroute;
    @XmlElement(required = true)
    protected String drawFixes;
    @XmlElement(required = true)
    protected String drawNavaids;
    @XmlElement(required = true)
    protected String drawRerouteLabel;
    @XmlElement(required = true)
    protected String drawRerouteByDefault;
    @XmlSchemaType(name = "integer")
    protected int colorId;
    @XmlElement(required = true)
    protected String rerouteTimeType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar rerouteStartTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar rerouteEndTime;
    protected String fcaName;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fcaStartTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fcaEndTime;
    protected String cancelDroppedFlights;
    protected RerouteGeneralDataType.CanceledRerouteList canceledRerouteList;
    protected String tmiIdHistory;

    /**
     * Gets the value of the rerouteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerouteId() {
        return rerouteId;
    }

    /**
     * Sets the value of the rerouteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerouteId(String value) {
        this.rerouteId = value;
    }

    /**
     * Gets the value of the rerouteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerouteName() {
        return rerouteName;
    }

    /**
     * Sets the value of the rerouteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerouteName(String value) {
        this.rerouteName = value;
    }

    /**
     * Gets the value of the rerouteStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerouteStatus() {
        return rerouteStatus;
    }

    /**
     * Sets the value of the rerouteStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerouteStatus(String value) {
        this.rerouteStatus = value;
    }

    /**
     * Gets the value of the tmiId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmiId() {
        return tmiId;
    }

    /**
     * Sets the value of the tmiId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmiId(String value) {
        this.tmiId = value;
    }

    /**
     * Gets the value of the tmiStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TmiStatusType }
     *     
     */
    public TmiStatusType getTmiStatus() {
        return tmiStatus;
    }

    /**
     * Sets the value of the tmiStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmiStatusType }
     *     
     */
    public void setTmiStatus(TmiStatusType value) {
        this.tmiStatus = value;
    }

    /**
     * Gets the value of the rerouteDataDomain property.
     * 
     * @return
     *     possible object is
     *     {@link TmiVisibilityDomainType }
     *     
     */
    public TmiVisibilityDomainType getRerouteDataDomain() {
        return rerouteDataDomain;
    }

    /**
     * Sets the value of the rerouteDataDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmiVisibilityDomainType }
     *     
     */
    public void setRerouteDataDomain(TmiVisibilityDomainType value) {
        this.rerouteDataDomain = value;
    }

    /**
     * Gets the value of the lastUpdateDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdateDateTime() {
        return lastUpdateDateTime;
    }

    /**
     * Sets the value of the lastUpdateDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdateDateTime(XMLGregorianCalendar value) {
        this.lastUpdateDateTime = value;
    }

    /**
     * Gets the value of the originalCreateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOriginalCreateTime() {
        return originalCreateTime;
    }

    /**
     * Sets the value of the originalCreateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOriginalCreateTime(XMLGregorianCalendar value) {
        this.originalCreateTime = value;
    }

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSite(String value) {
        this.site = value;
    }

    /**
     * Gets the value of the rerouteWorkstationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerouteWorkstationId() {
        return rerouteWorkstationId;
    }

    /**
     * Sets the value of the rerouteWorkstationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerouteWorkstationId(String value) {
        this.rerouteWorkstationId = value;
    }

    /**
     * Gets the value of the rerouteAirborne property.
     * 
     * @return
     *     possible object is
     *     {@link AffectedFlightStatus }
     *     
     */
    public AffectedFlightStatus getRerouteAirborne() {
        return rerouteAirborne;
    }

    /**
     * Sets the value of the rerouteAirborne property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffectedFlightStatus }
     *     
     */
    public void setRerouteAirborne(AffectedFlightStatus value) {
        this.rerouteAirborne = value;
    }

    /**
     * Gets the value of the applyProtectedSegments property.
     * 
     */
    public boolean isApplyProtectedSegments() {
        return applyProtectedSegments;
    }

    /**
     * Sets the value of the applyProtectedSegments property.
     * 
     */
    public void setApplyProtectedSegments(boolean value) {
        this.applyProtectedSegments = value;
    }

    /**
     * Gets the value of the protectedSegment property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProtectedSegment() {
        return protectedSegment;
    }

    /**
     * Sets the value of the protectedSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProtectedSegment(Object value) {
        this.protectedSegment = value;
    }

    /**
     * Gets the value of the monitorReroute property.
     * 
     */
    public boolean isMonitorReroute() {
        return monitorReroute;
    }

    /**
     * Sets the value of the monitorReroute property.
     * 
     */
    public void setMonitorReroute(boolean value) {
        this.monitorReroute = value;
    }

    /**
     * Gets the value of the drawFixes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawFixes() {
        return drawFixes;
    }

    /**
     * Sets the value of the drawFixes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawFixes(String value) {
        this.drawFixes = value;
    }

    /**
     * Gets the value of the drawNavaids property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawNavaids() {
        return drawNavaids;
    }

    /**
     * Sets the value of the drawNavaids property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawNavaids(String value) {
        this.drawNavaids = value;
    }

    /**
     * Gets the value of the drawRerouteLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawRerouteLabel() {
        return drawRerouteLabel;
    }

    /**
     * Sets the value of the drawRerouteLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawRerouteLabel(String value) {
        this.drawRerouteLabel = value;
    }

    /**
     * Gets the value of the drawRerouteByDefault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawRerouteByDefault() {
        return drawRerouteByDefault;
    }

    /**
     * Sets the value of the drawRerouteByDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawRerouteByDefault(String value) {
        this.drawRerouteByDefault = value;
    }

    /**
     * Gets the value of the colorId property.
     * 
     */
    public int getColorId() {
        return colorId;
    }

    /**
     * Sets the value of the colorId property.
     * 
     */
    public void setColorId(int value) {
        this.colorId = value;
    }

    /**
     * Gets the value of the rerouteTimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerouteTimeType() {
        return rerouteTimeType;
    }

    /**
     * Sets the value of the rerouteTimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerouteTimeType(String value) {
        this.rerouteTimeType = value;
    }

    /**
     * Gets the value of the rerouteStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRerouteStartTime() {
        return rerouteStartTime;
    }

    /**
     * Sets the value of the rerouteStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRerouteStartTime(XMLGregorianCalendar value) {
        this.rerouteStartTime = value;
    }

    /**
     * Gets the value of the rerouteEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRerouteEndTime() {
        return rerouteEndTime;
    }

    /**
     * Sets the value of the rerouteEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRerouteEndTime(XMLGregorianCalendar value) {
        this.rerouteEndTime = value;
    }

    /**
     * Gets the value of the fcaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFcaName() {
        return fcaName;
    }

    /**
     * Sets the value of the fcaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFcaName(String value) {
        this.fcaName = value;
    }

    /**
     * Gets the value of the fcaStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFcaStartTime() {
        return fcaStartTime;
    }

    /**
     * Sets the value of the fcaStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFcaStartTime(XMLGregorianCalendar value) {
        this.fcaStartTime = value;
    }

    /**
     * Gets the value of the fcaEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFcaEndTime() {
        return fcaEndTime;
    }

    /**
     * Sets the value of the fcaEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFcaEndTime(XMLGregorianCalendar value) {
        this.fcaEndTime = value;
    }

    /**
     * Gets the value of the cancelDroppedFlights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelDroppedFlights() {
        return cancelDroppedFlights;
    }

    /**
     * Sets the value of the cancelDroppedFlights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelDroppedFlights(String value) {
        this.cancelDroppedFlights = value;
    }

    /**
     * Gets the value of the canceledRerouteList property.
     * 
     * @return
     *     possible object is
     *     {@link RerouteGeneralDataType.CanceledRerouteList }
     *     
     */
    public RerouteGeneralDataType.CanceledRerouteList getCanceledRerouteList() {
        return canceledRerouteList;
    }

    /**
     * Sets the value of the canceledRerouteList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RerouteGeneralDataType.CanceledRerouteList }
     *     
     */
    public void setCanceledRerouteList(RerouteGeneralDataType.CanceledRerouteList value) {
        this.canceledRerouteList = value;
    }

    /**
     * Gets the value of the tmiIdHistory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmiIdHistory() {
        return tmiIdHistory;
    }

    /**
     * Sets the value of the tmiIdHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmiIdHistory(String value) {
        this.tmiIdHistory = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="canceledRerouteId" type="{urn:us:gov:dot:faa:atm:tfm:ficommonmessages}rerouteIdType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "canceledRerouteId"
    })
    public static class CanceledRerouteList {

        @XmlElement(required = true)
        protected List<String> canceledRerouteId;

        /**
         * Gets the value of the canceledRerouteId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the canceledRerouteId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCanceledRerouteId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCanceledRerouteId() {
            if (canceledRerouteId == null) {
                canceledRerouteId = new ArrayList<String>();
            }
            return this.canceledRerouteId;
        }

    }

}
