//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package aero.fixm.tfm._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TfmSensitivityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TfmSensitivityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="D"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TfmSensitivityType")
@XmlEnum
public enum TfmSensitivityType {


    /**
     * Sensitive data for distribution to government agency only.
     * 
     */
    R,

    /**
     * Data that can be distributed to all users including delayed users.
     * 
     */
    A,

    /**
     * Duplication of sensitive data but sanitized, i.e. sensitive data removed. It can be distributed
     *                          to all users except government agency.
     * 
     */
    D;

    public String value() {
        return name();
    }

    public static TfmSensitivityType fromValue(String v) {
        return valueOf(v);
    }

}
