//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.flightdatacommonmessages;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import us.gov.dot.faa.atm.tfm.tfmdatacoreelements.OceanicPositionDataType;
import us.gov.dot.faa.atm.tfm.tfmdatacoreelements.QualifiedAircraftIdType;


/**
 * Oceanic Report Type provides flight information for transoceanic flights and is generated when an Oceanic Position Report is received via NADIN.
 * 
 * <p>Java class for oceanicReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oceanicReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="qualifiedAircraftId" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}qualifiedAircraftIdType"/>
 *         &lt;element name="speed" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}groundSpeedType"/>
 *         &lt;element name="plannedPositionData" maxOccurs="2" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}oceanicPositionDataType">
 *                 &lt;attribute name="planNumber" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reportedPositionData" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}oceanicPositionDataType"/>
 *         &lt;choice>
 *           &lt;element name="ncsmTrackData" type="{urn:us:gov:dot:faa:atm:tfm:flightdatacommonmessages}ncsmTrackDataType"/>
 *           &lt;element name="ncsmRouteData" type="{urn:us:gov:dot:faa:atm:tfm:flightdatacommonmessages}ncsmFlightRouteDataType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oceanicReportType", propOrder = {
    "qualifiedAircraftId",
    "speed",
    "plannedPositionData",
    "reportedPositionData",
    "ncsmTrackData",
    "ncsmRouteData"
})
public class OceanicReportType {

    @XmlElement(required = true)
    protected QualifiedAircraftIdType qualifiedAircraftId;
    @XmlSchemaType(name = "integer")
    protected int speed;
    protected List<OceanicReportType.PlannedPositionData> plannedPositionData;
    @XmlElement(required = true)
    protected OceanicPositionDataType reportedPositionData;
    protected NcsmTrackDataType ncsmTrackData;
    protected NcsmFlightRouteDataType ncsmRouteData;

    /**
     * Gets the value of the qualifiedAircraftId property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiedAircraftIdType }
     *     
     */
    public QualifiedAircraftIdType getQualifiedAircraftId() {
        return qualifiedAircraftId;
    }

    /**
     * Sets the value of the qualifiedAircraftId property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiedAircraftIdType }
     *     
     */
    public void setQualifiedAircraftId(QualifiedAircraftIdType value) {
        this.qualifiedAircraftId = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     */
    public int getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     */
    public void setSpeed(int value) {
        this.speed = value;
    }

    /**
     * Gets the value of the plannedPositionData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plannedPositionData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlannedPositionData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OceanicReportType.PlannedPositionData }
     * 
     * 
     */
    public List<OceanicReportType.PlannedPositionData> getPlannedPositionData() {
        if (plannedPositionData == null) {
            plannedPositionData = new ArrayList<OceanicReportType.PlannedPositionData>();
        }
        return this.plannedPositionData;
    }

    /**
     * Gets the value of the reportedPositionData property.
     * 
     * @return
     *     possible object is
     *     {@link OceanicPositionDataType }
     *     
     */
    public OceanicPositionDataType getReportedPositionData() {
        return reportedPositionData;
    }

    /**
     * Sets the value of the reportedPositionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link OceanicPositionDataType }
     *     
     */
    public void setReportedPositionData(OceanicPositionDataType value) {
        this.reportedPositionData = value;
    }

    /**
     * Gets the value of the ncsmTrackData property.
     * 
     * @return
     *     possible object is
     *     {@link NcsmTrackDataType }
     *     
     */
    public NcsmTrackDataType getNcsmTrackData() {
        return ncsmTrackData;
    }

    /**
     * Sets the value of the ncsmTrackData property.
     * 
     * @param value
     *     allowed object is
     *     {@link NcsmTrackDataType }
     *     
     */
    public void setNcsmTrackData(NcsmTrackDataType value) {
        this.ncsmTrackData = value;
    }

    /**
     * Gets the value of the ncsmRouteData property.
     * 
     * @return
     *     possible object is
     *     {@link NcsmFlightRouteDataType }
     *     
     */
    public NcsmFlightRouteDataType getNcsmRouteData() {
        return ncsmRouteData;
    }

    /**
     * Sets the value of the ncsmRouteData property.
     * 
     * @param value
     *     allowed object is
     *     {@link NcsmFlightRouteDataType }
     *     
     */
    public void setNcsmRouteData(NcsmFlightRouteDataType value) {
        this.ncsmRouteData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}oceanicPositionDataType">
     *       &lt;attribute name="planNumber" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PlannedPositionData
        extends OceanicPositionDataType
    {

        @XmlAttribute(name = "planNumber")
        protected BigInteger planNumber;

        /**
         * Gets the value of the planNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPlanNumber() {
            return planNumber;
        }

        /**
         * Sets the value of the planNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPlanNumber(BigInteger value) {
            this.planNumber = value;
        }

    }

}
