//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.tfmdatacoreelements;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for coordinationTimeDescriptorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="coordinationTimeDescriptorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ESTIMATED"/>
 *     &lt;enumeration value="PROPOSED"/>
 *     &lt;enumeration value="ACTUAL"/>
 *     &lt;enumeration value="FLUSH"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "coordinationTimeDescriptorType")
@XmlEnum
public enum CoordinationTimeDescriptorType {

    ESTIMATED,
    PROPOSED,
    ACTUAL,
    FLUSH,
    OTHER;

    public String value() {
        return name();
    }

    public static CoordinationTimeDescriptorType fromValue(String v) {
        return valueOf(v);
    }

}
