//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:45:39 PM IST 
//


package us.gov.dot.faa.atm.tfm.tfmdatacoreelements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.Duration;


/**
 * EnRoute Element Type indicates the type of enRoute element.
 * 
 * <p>Java class for enRouteElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="enRouteElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="48" minOccurs="0">
 *         &lt;element name="fix">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}fixType">
 *                 &lt;attribute name="delayDataType" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="adaptedRoute">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements>routeNameType">
 *                 &lt;attribute name="loopReEntry1" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}loopReEntryType" />
 *                 &lt;attribute name="loopReEntry2" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}loopReEntryType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enRouteElementType", propOrder = {
    "fixOrAdaptedRoute"
})
public class EnRouteElementType {

    @XmlElements({
        @XmlElement(name = "fix", type = EnRouteElementType.Fix.class),
        @XmlElement(name = "adaptedRoute", type = EnRouteElementType.AdaptedRoute.class)
    })
    protected List<Object> fixOrAdaptedRoute;

    /**
     * Gets the value of the fixOrAdaptedRoute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fixOrAdaptedRoute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFixOrAdaptedRoute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnRouteElementType.Fix }
     * {@link EnRouteElementType.AdaptedRoute }
     * 
     * 
     */
    public List<Object> getFixOrAdaptedRoute() {
        if (fixOrAdaptedRoute == null) {
            fixOrAdaptedRoute = new ArrayList<Object>();
        }
        return this.fixOrAdaptedRoute;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements>routeNameType">
     *       &lt;attribute name="loopReEntry1" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}loopReEntryType" />
     *       &lt;attribute name="loopReEntry2" type="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}loopReEntryType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AdaptedRoute {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "loopReEntry1")
        protected Integer loopReEntry1;
        @XmlAttribute(name = "loopReEntry2")
        protected Integer loopReEntry2;

        /**
         * Simple type defining the structure for describing the elements necessary to define the identity of a flight's route.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the loopReEntry1 property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLoopReEntry1() {
            return loopReEntry1;
        }

        /**
         * Sets the value of the loopReEntry1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLoopReEntry1(Integer value) {
            this.loopReEntry1 = value;
        }

        /**
         * Gets the value of the loopReEntry2 property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLoopReEntry2() {
            return loopReEntry2;
        }

        /**
         * Sets the value of the loopReEntry2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLoopReEntry2(Integer value) {
            this.loopReEntry2 = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:us:gov:dot:faa:atm:tfm:tfmdatacoreelements}fixType">
     *       &lt;attribute name="delayDataType" type="{http://www.w3.org/2001/XMLSchema}duration" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Fix
        extends FixType
    {

        @XmlAttribute(name = "delayDataType")
        protected Duration delayDataType;

        /**
         * Gets the value of the delayDataType property.
         * 
         * @return
         *     possible object is
         *     {@link Duration }
         *     
         */
        public Duration getDelayDataType() {
            return delayDataType;
        }

        /**
         * Sets the value of the delayDataType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Duration }
         *     
         */
        public void setDelayDataType(Duration value) {
            this.delayDataType = value;
        }

    }

}
